import { RepoItem } from './types';

export const SEED_REPOSITORIES: RepoItem[] = [
  // ==========================================
  // 1. ARCHITECTURE, SYSTEM DESIGN & ROADMAPS
  // ==========================================
  {
    id: 'donnemartin/system-design-primer',
    fullName: 'donnemartin/system-design-primer',
    name: 'system-design-primer',
    owner: 'donnemartin',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/544330?v=4',
    description: 'Learn how to design large-scale systems. Prep for the system design interview. Includes Anki flashcards.',
    url: 'https://github.com/donnemartin/system-design-primer',
    stars: 285000,
    forks: 46000,
    openIssues: 380,
    language: 'Python',
    topics: ['system-design', 'architecture', 'interview-prep', 'scalability', 'distributed-systems', 'devops'],
    updatedAt: new Date().toISOString(),
    createdAt: '2017-02-26T16:15:28Z',
    category: 'architecture',
    categories: ['architecture', 'devops-infra', 'hall-of-fame'],
    isVerified: true,
    velocityScore: 98,
    velocityLabel: 'CLASSIC',
  },
  {
    id: 'kamranahmedse/developer-roadmap',
    fullName: 'kamranahmedse/developer-roadmap',
    name: 'developer-roadmap',
    owner: 'kamranahmedse',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/4921183?v=4',
    description: 'Interactive roadmaps, guides and other educational content to help developers grow in their career including DevOps, AI, and Cloud.',
    url: 'https://github.com/kamranahmedse/developer-roadmap',
    stars: 310000,
    forks: 39000,
    openIssues: 540,
    language: 'TypeScript',
    topics: ['devops-roadmap', 'ai-engineer', 'cloud-architecture', 'learning-paths', 'career-guide'],
    updatedAt: new Date().toISOString(),
    createdAt: '2017-03-15T13:45:00Z',
    category: 'architecture',
    categories: ['architecture', 'hall-of-fame'],
    isVerified: true,
    velocityScore: 95,
    velocityLabel: 'CLASSIC',
  },
  {
    id: 'bregman-arie/devops-exercises',
    fullName: 'bregman-arie/devops-exercises',
    name: 'devops-exercises',
    owner: 'bregman-arie',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/10349437?v=4',
    description: 'Linux, Jenkins, AWS, SRE, Prometheus, Docker, Python, Ansible, Git, Kubernetes, Terraform, OpenStack, SQL, Questions and Answers.',
    url: 'https://github.com/bregman-arie/devops-exercises',
    stars: 65000,
    forks: 15500,
    openIssues: 120,
    language: 'Python',
    topics: ['devops', 'kubernetes', 'sre', 'ansible', 'terraform', 'interview-questions', 'docker'],
    updatedAt: new Date().toISOString(),
    createdAt: '2019-10-24T18:00:00Z',
    category: 'architecture',
    categories: ['architecture', 'devops-infra', 'hall-of-fame'],
    isVerified: true,
    velocityScore: 90,
    velocityLabel: 'CLASSIC',
  },
  {
    id: 'kelseyhightower/kubernetes-the-hard-way',
    fullName: 'kelseyhightower/kubernetes-the-hard-way',
    name: 'kubernetes-the-hard-way',
    owner: 'kelseyhightower',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/1123322?v=4',
    description: 'Bootstrap Kubernetes the hard way on Google Cloud Platform or local VMs. No scripts, no magic.',
    url: 'https://github.com/kelseyhightower/kubernetes-the-hard-way',
    stars: 42000,
    forks: 14000,
    openIssues: 45,
    language: 'Shell',
    topics: ['kubernetes', 'cloud-native', 'security', 'tls', 'etcd', 'container-runtime', 'devops'],
    updatedAt: new Date().toISOString(),
    createdAt: '2016-08-01T20:00:00Z',
    category: 'architecture',
    categories: ['architecture', 'devops-infra', 'hall-of-fame'],
    isVerified: true,
    velocityScore: 88,
    velocityLabel: 'CLASSIC',
  },
  {
    id: 'trimstray/the-book-of-secret-knowledge',
    fullName: 'trimstray/the-book-of-secret-knowledge',
    name: 'the-book-of-secret-knowledge',
    owner: 'trimstray',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/16100109?v=4',
    description: 'A collection of inspiring lists, manuals, cheatsheets, blogs, hacks, one-liners, cli/web tools and more.',
    url: 'https://github.com/trimstray/the-book-of-secret-knowledge',
    stars: 155000,
    forks: 17000,
    openIssues: 80,
    language: 'Shell',
    topics: ['devops', 'sysadmin', 'security', 'cheatsheet', 'linux', 'cloud', 'cli'],
    updatedAt: new Date().toISOString(),
    createdAt: '2018-08-11T12:00:00Z',
    category: 'architecture',
    categories: ['architecture', 'hall-of-fame'],
    isVerified: true,
    velocityScore: 92,
    velocityLabel: 'CLASSIC',
  },

  // ==========================================
  // 2. AGENTIC AI, LLM & AUTONOMOUS AGENTS
  // ==========================================
  {
    id: 'ollama/ollama',
    fullName: 'ollama/ollama',
    name: 'ollama',
    owner: 'ollama',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/132925968?v=4',
    description: 'Get up and running with Llama 3.3, DeepSeek-R1, Mistral, Gemma 2, and other large language models locally.',
    url: 'https://github.com/ollama/ollama',
    stars: 128000,
    forks: 11000,
    openIssues: 950,
    language: 'Go',
    topics: ['llm', 'local-ai', 'deepseek', 'llama3', 'inference', 'go', 'agentic-ai'],
    updatedAt: new Date().toISOString(),
    createdAt: '2023-06-19T21:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'mlops', 'hall-of-fame', 'trending'],
    isVerified: true,
    velocityScore: 99,
    velocityLabel: 'EXPLOSIVE',
  },
  {
    id: 'vllm-project/vllm',
    fullName: 'vllm-project/vllm',
    name: 'vllm',
    owner: 'vllm-project',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/136070635?v=4',
    description: 'A high-throughput and memory-efficient inference and serving engine for LLMs.',
    url: 'https://github.com/vllm-project/vllm',
    stars: 39500,
    forks: 5800,
    openIssues: 1100,
    language: 'Python',
    topics: ['llm', 'inference', 'pagedattention', 'serving', 'distributed-serving', 'gpu'],
    updatedAt: new Date().toISOString(),
    createdAt: '2023-06-12T16:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'mlops', 'trending'],
    isVerified: true,
    velocityScore: 96,
    velocityLabel: 'HOT RISING',
  },
  {
    id: 'langchain-ai/langchain',
    fullName: 'langchain-ai/langchain',
    name: 'langchain',
    owner: 'langchain-ai',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/126733545?v=4',
    description: 'Build context-aware reasoning applications with LCEL, LangGraph, and broad ecosystem connectors.',
    url: 'https://github.com/langchain-ai/langchain',
    stars: 98000,
    forks: 16000,
    openIssues: 1800,
    language: 'Python',
    topics: ['llm', 'rag', 'langchain', 'langgraph', 'agents', 'vector-search'],
    updatedAt: new Date().toISOString(),
    createdAt: '2022-10-25T14:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'mlops', 'hall-of-fame'],
    isVerified: true,
    velocityScore: 92,
    velocityLabel: 'CLASSIC',
  },
  {
    id: 'All-Hands-AI/OpenHands',
    fullName: 'All-Hands-AI/OpenHands',
    name: 'OpenHands',
    owner: 'All-Hands-AI',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/166662489?v=4',
    description: 'OpenHands: Code Less, Make More. An open-source autonomous software developer agent.',
    url: 'https://github.com/All-Hands-AI/OpenHands',
    stars: 44000,
    forks: 5200,
    openIssues: 410,
    language: 'Python',
    topics: ['autonomous-agent', 'swe-agent', 'code-generation', 'developer-tools', 'docker-sandbox'],
    updatedAt: new Date().toISOString(),
    createdAt: '2024-03-12T08:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'trending', 'hall-of-fame'],
    isVerified: true,
    velocityScore: 97,
    velocityLabel: 'EXPLOSIVE',
  },
  {
    id: 'crewAIInc/crewAI',
    fullName: 'crewAIInc/crewAI',
    name: 'crewAI',
    owner: 'crewAIInc',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/152917711?v=4',
    description: 'Framework for orchestrating role-playing, autonomous AI agents. By fostering collaborative intelligence.',
    url: 'https://github.com/crewAIInc/crewAI',
    stars: 26500,
    forks: 3400,
    openIssues: 260,
    language: 'Python',
    topics: ['ai-agents', 'autonomous-agents', 'crewai', 'multi-agent', 'llm-orchestration'],
    updatedAt: new Date().toISOString(),
    createdAt: '2023-11-20T10:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'trending'],
    isVerified: true,
    velocityScore: 94,
    velocityLabel: 'HOT RISING',
  },
  {
    id: 'microsoft/autogen',
    fullName: 'microsoft/autogen',
    name: 'autogen',
    owner: 'microsoft',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/6154722?v=4',
    description: 'A programming framework for agentic AI. Enabling next-gen LLM applications via multi-agent conversation.',
    url: 'https://github.com/microsoft/autogen',
    stars: 38000,
    forks: 5600,
    openIssues: 320,
    language: 'Python',
    topics: ['agentic-ai', 'multi-agent', 'conversational-ai', 'microsoft', 'code-execution'],
    updatedAt: new Date().toISOString(),
    createdAt: '2023-08-16T12:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'hall-of-fame'],
    isVerified: true,
    velocityScore: 91,
    velocityLabel: 'CLASSIC',
  },
  {
    id: 'browser-use/browser-use',
    fullName: 'browser-use/browser-use',
    name: 'browser-use',
    owner: 'browser-use',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/187994809?v=4',
    description: 'Make websites accessible for AI agents. Open-source library that empowers AI agents to browse the web.',
    url: 'https://github.com/browser-use/browser-use',
    stars: 32000,
    forks: 3100,
    openIssues: 180,
    language: 'Python',
    topics: ['browser-automation', 'ai-agent', 'web-scraping', 'agentic-ai', 'playwright'],
    updatedAt: new Date().toISOString(),
    createdAt: '2024-11-01T10:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'trending'],
    isVerified: true,
    velocityScore: 99,
    velocityLabel: 'EXPLOSIVE',
  },
  {
    id: 'cline/cline',
    fullName: 'cline/cline',
    name: 'cline',
    owner: 'cline',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/178125867?v=4',
    description: 'Autonomous coding agent right in your IDE, capable of creating/editing files, running commands, and using browser.',
    url: 'https://github.com/cline/cline',
    stars: 28000,
    forks: 2900,
    openIssues: 210,
    language: 'TypeScript',
    topics: ['coding-agent', 'autonomous-agent', 'vscode-extension', 'anthropic', 'ai-agent'],
    updatedAt: new Date().toISOString(),
    createdAt: '2024-07-15T12:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'trending'],
    isVerified: true,
    velocityScore: 98,
    velocityLabel: 'EXPLOSIVE',
  },
  {
    id: 'langgenius/dify',
    fullName: 'langgenius/dify',
    name: 'dify',
    owner: 'langgenius',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/118463102?v=4',
    description: 'Dify is an open-source LLM app development platform. Orchestrate AI agents, RAG, and workflow engines.',
    url: 'https://github.com/langgenius/dify',
    stars: 62000,
    forks: 8900,
    openIssues: 650,
    language: 'TypeScript',
    topics: ['llmops', 'agentic-ai', 'rag', 'workflow-engine', 'low-code', 'ai-agents'],
    updatedAt: new Date().toISOString(),
    createdAt: '2023-03-01T08:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'mlops', 'hall-of-fame', 'trending'],
    isVerified: true,
    velocityScore: 97,
    velocityLabel: 'HOT RISING',
  },
  {
    id: 'modelcontextprotocol/servers',
    fullName: 'modelcontextprotocol/servers',
    name: 'servers',
    owner: 'modelcontextprotocol',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/189700816?v=4',
    description: 'Model Context Protocol (MCP) Reference Servers. Connect Claude, AI Agents to tools, DBs, and APIs.',
    url: 'https://github.com/modelcontextprotocol/servers',
    stars: 24000,
    forks: 2300,
    openIssues: 110,
    language: 'TypeScript',
    topics: ['mcp', 'anthropic', 'model-context-protocol', 'ai-agents', 'tools'],
    updatedAt: new Date().toISOString(),
    createdAt: '2024-11-20T16:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'trending'],
    isVerified: true,
    velocityScore: 99,
    velocityLabel: 'EXPLOSIVE',
  },
  {
    id: 'pydantic/pydantic-ai',
    fullName: 'pydantic/pydantic-ai',
    name: 'pydantic-ai',
    owner: 'pydantic',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/11081844?v=4',
    description: 'Agent Framework / shim to use Pydantic with LLMs. Type-safe, structured outputs, validation for GenAI.',
    url: 'https://github.com/pydantic/pydantic-ai',
    stars: 8500,
    forks: 650,
    openIssues: 75,
    language: 'Python',
    topics: ['pydantic', 'ai-agent', 'type-safe', 'llm-framework', 'structured-outputs'],
    updatedAt: new Date().toISOString(),
    createdAt: '2024-12-01T14:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'trending'],
    isVerified: true,
    velocityScore: 96,
    velocityLabel: 'EXPLOSIVE',
  },

  // ==========================================
  // 3. DEVOPS & CLOUD-NATIVE INFRASTRUCTURE
  // ==========================================
  {
    id: 'kubernetes/kubernetes',
    fullName: 'kubernetes/kubernetes',
    name: 'kubernetes',
    owner: 'kubernetes',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/13629408?v=4',
    description: 'Production-Grade Container Scheduling and Management. The foundation of modern cloud-native systems.',
    url: 'https://github.com/kubernetes/kubernetes',
    stars: 112000,
    forks: 39000,
    openIssues: 2400,
    language: 'Go',
    topics: ['kubernetes', 'cloud-native', 'container-orchestration', 'cncf', 'go', 'devops'],
    updatedAt: new Date().toISOString(),
    createdAt: '2014-06-06T20:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'hall-of-fame'],
    isVerified: true,
    velocityScore: 94,
    velocityLabel: 'CLASSIC',
  },
  {
    id: 'argoproj/argo-cd',
    fullName: 'argoproj/argo-cd',
    name: 'argo-cd',
    owner: 'argoproj',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/30269780?v=4',
    description: 'Declarative, continuous delivery with a GitOps workflow for Kubernetes.',
    url: 'https://github.com/argoproj/argo-cd',
    stars: 18500,
    forks: 5400,
    openIssues: 1600,
    language: 'Go',
    topics: ['gitops', 'kubernetes', 'continuous-delivery', 'cncf-graduated', 'cloud-native'],
    updatedAt: new Date().toISOString(),
    createdAt: '2018-02-14T22:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'trending'],
    isVerified: true,
    velocityScore: 93,
    velocityLabel: 'HOT RISING',
  },
  {
    id: 'hashicorp/terraform',
    fullName: 'hashicorp/terraform',
    name: 'terraform',
    owner: 'hashicorp',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/761456?v=4',
    description: 'Terraform enables you to safely and predictably create, change, and improve infrastructure. (IaC)',
    url: 'https://github.com/hashicorp/terraform',
    stars: 42500,
    forks: 9400,
    openIssues: 1500,
    language: 'Go',
    topics: ['iac', 'infrastructure-as-code', 'cloud', 'aws', 'gcp', 'azure', 'devops'],
    updatedAt: new Date().toISOString(),
    createdAt: '2014-05-13T16:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'hall-of-fame'],
    isVerified: true,
    velocityScore: 89,
    velocityLabel: 'CLASSIC',
  },
  {
    id: 'opentofu/opentofu',
    fullName: 'opentofu/opentofu',
    name: 'opentofu',
    owner: 'opentofu',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/144186526?v=4',
    description: 'OpenTofu is an open-source successor to Terraform managed by the Linux Foundation.',
    url: 'https://github.com/opentofu/opentofu',
    stars: 24000,
    forks: 1100,
    openIssues: 180,
    language: 'Go',
    topics: ['opentofu', 'terraform', 'iac', 'linux-foundation', 'open-source', 'cloud'],
    updatedAt: new Date().toISOString(),
    createdAt: '2023-08-25T14:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'trending'],
    isVerified: true,
    velocityScore: 95,
    velocityLabel: 'HOT RISING',
  },
  {
    id: 'cilium/cilium',
    fullName: 'cilium/cilium',
    name: 'cilium',
    owner: 'cilium',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/17392688?v=4',
    description: 'eBPF-based Networking, Observability, and Security for Kubernetes and Cloud Native.',
    url: 'https://github.com/cilium/cilium',
    stars: 20500,
    forks: 3000,
    openIssues: 1200,
    language: 'Go',
    topics: ['ebpf', 'kubernetes', 'networking', 'security', 'observability', 'service-mesh'],
    updatedAt: new Date().toISOString(),
    createdAt: '2016-03-24T20:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'trending'],
    isVerified: true,
    velocityScore: 94,
    velocityLabel: 'HOT RISING',
  },
  {
    id: 'crossplane/crossplane',
    fullName: 'crossplane/crossplane',
    name: 'crossplane',
    owner: 'crossplane',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/43970868?v=4',
    description: 'Cloud Native Control Planes. Turn Kubernetes into a universal control plane for any infrastructure.',
    url: 'https://github.com/crossplane/crossplane',
    stars: 10200,
    forks: 1200,
    openIssues: 380,
    language: 'Go',
    topics: ['control-plane', 'kubernetes', 'iac', 'cloud-native', 'cncf', 'internal-developer-platform'],
    updatedAt: new Date().toISOString(),
    createdAt: '2018-11-29T18:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra'],
    isVerified: true,
    velocityScore: 90,
    velocityLabel: 'TOP RATED',
  },
  {
    id: 'backstage/backstage',
    fullName: 'backstage/backstage',
    name: 'backstage',
    owner: 'backstage',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/61783427?v=4',
    description: 'Backstage is an open platform for building developer portals created by Spotify.',
    url: 'https://github.com/backstage/backstage',
    stars: 28500,
    forks: 5800,
    openIssues: 890,
    language: 'TypeScript',
    topics: ['developer-portal', 'platform-engineering', 'internal-developer-platform', 'spotify', 'cncf'],
    updatedAt: new Date().toISOString(),
    createdAt: '2020-03-16T12:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'trending'],
    isVerified: true,
    velocityScore: 92,
    velocityLabel: 'HOT RISING',
  },
  {
    id: 'pulumi/pulumi',
    fullName: 'pulumi/pulumi',
    name: 'pulumi',
    owner: 'pulumi',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/29302652?v=4',
    description: 'Pulumi - Infrastructure as Code in any programming language: TypeScript, Python, Go, C#, Java, YAML.',
    url: 'https://github.com/pulumi/pulumi',
    stars: 22500,
    forks: 1400,
    openIssues: 680,
    language: 'Go',
    topics: ['iac', 'infrastructure-as-code', 'cloud', 'aws', 'kubernetes', 'azure'],
    updatedAt: new Date().toISOString(),
    createdAt: '2018-05-01T10:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra'],
    isVerified: true,
    velocityScore: 89,
    velocityLabel: 'TOP RATED',
  },

  // ==========================================
  // 4. MLOPS & LLMOPS
  // ==========================================
  {
    id: 'mlflow/mlflow',
    fullName: 'mlflow/mlflow',
    name: 'mlflow',
    owner: 'mlflow',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/38743126?v=4',
    description: 'Open source platform for the complete machine learning and GenAI lifecycle.',
    url: 'https://github.com/mlflow/mlflow',
    stars: 19800,
    forks: 4100,
    openIssues: 580,
    language: 'Python',
    topics: ['mlops', 'llmops', 'experiment-tracking', 'model-registry', 'genai', 'evaluation'],
    updatedAt: new Date().toISOString(),
    createdAt: '2018-05-30T22:00:00Z',
    category: 'mlops',
    categories: ['mlops', 'hall-of-fame'],
    isVerified: true,
    velocityScore: 91,
    velocityLabel: 'CLASSIC',
  },
  {
    id: 'qdrant/qdrant',
    fullName: 'qdrant/qdrant',
    name: 'qdrant',
    owner: 'qdrant',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/74640498?v=4',
    description: 'Qdrant - High-performance, massive-scale Vector Database and Vector Search Engine for AI.',
    url: 'https://github.com/qdrant/qdrant',
    stars: 22000,
    forks: 1700,
    openIssues: 220,
    language: 'Rust',
    topics: ['vector-database', 'vector-search', 'rust', 'embeddings', 'rag', 'llmops'],
    updatedAt: new Date().toISOString(),
    createdAt: '2020-05-20T14:00:00Z',
    category: 'mlops',
    categories: ['mlops', 'trending'],
    isVerified: true,
    velocityScore: 96,
    velocityLabel: 'HOT RISING',
  },
  {
    id: 'chroma-core/chroma',
    fullName: 'chroma-core/chroma',
    name: 'chroma',
    owner: 'chroma-core',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/104118928?v=4',
    description: 'The open-source AI embedding database.',
    url: 'https://github.com/chroma-core/chroma',
    stars: 17200,
    forks: 1600,
    openIssues: 450,
    language: 'Python',
    topics: ['vector-database', 'embeddings', 'rag', 'python', 'ai-native'],
    updatedAt: new Date().toISOString(),
    createdAt: '2022-10-18T18:00:00Z',
    category: 'mlops',
    categories: ['mlops'],
    isVerified: true,
    velocityScore: 89,
    velocityLabel: 'TOP RATED',
  },
  {
    id: 'milvus-io/milvus',
    fullName: 'milvus-io/milvus',
    name: 'milvus',
    owner: 'milvus-io',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/52219914?v=4',
    description: 'Milvus is a cloud-native, open-source vector database built to manage embedding vectors generated by AI.',
    url: 'https://github.com/milvus-io/milvus',
    stars: 32500,
    forks: 3300,
    openIssues: 540,
    language: 'Go',
    topics: ['vector-database', 'vector-search', 'embedding', 'ai', 'rag', 'cloud-native'],
    updatedAt: new Date().toISOString(),
    createdAt: '2019-06-25T10:00:00Z',
    category: 'mlops',
    categories: ['mlops', 'hall-of-fame'],
    isVerified: true,
    velocityScore: 92,
    velocityLabel: 'CLASSIC',
  },
  {
    id: 'bentoml/BentoML',
    fullName: 'bentoml/BentoML',
    name: 'BentoML',
    owner: 'bentoml',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/48590623?v=4',
    description: 'The unified framework for building, shipping, and scaling AI applications and production models.',
    url: 'https://github.com/bentoml/BentoML',
    stars: 7600,
    forks: 850,
    openIssues: 140,
    language: 'Python',
    topics: ['model-serving', 'mlops', 'llmops', 'fastapi', 'distributed-serving', 'docker'],
    updatedAt: new Date().toISOString(),
    createdAt: '2019-03-27T08:00:00Z',
    category: 'mlops',
    categories: ['mlops'],
    isVerified: true,
    velocityScore: 87,
    velocityLabel: 'TOP RATED',
  },
  {
    id: 'Arize-ai/phoenix',
    fullName: 'Arize-ai/phoenix',
    name: 'phoenix',
    owner: 'Arize-ai',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/59938069?v=4',
    description: 'AI Observability & Evaluation. OpenTelemetry-based tracing, evals, and prompt analytics for LLM applications.',
    url: 'https://github.com/Arize-ai/phoenix',
    stars: 5800,
    forks: 520,
    openIssues: 90,
    language: 'Python',
    topics: ['llm-observability', 'opentelemetry', 'evals', 'rag-evaluation', 'tracing', 'llmops'],
    updatedAt: new Date().toISOString(),
    createdAt: '2023-01-20T18:00:00Z',
    category: 'mlops',
    categories: ['mlops', 'trending'],
    isVerified: true,
    velocityScore: 92,
    velocityLabel: 'HOT RISING',
  },

  // ==========================================
  // 5. OBSERVABILITY & DEVSECOPS
  // ==========================================
  {
    id: 'prometheus/prometheus',
    fullName: 'prometheus/prometheus',
    name: 'prometheus',
    owner: 'prometheus',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/3380462?v=4',
    description: 'The Prometheus monitoring system and time series database. CNCF graduated foundation of observability.',
    url: 'https://github.com/prometheus/prometheus',
    stars: 57000,
    forks: 9200,
    openIssues: 800,
    language: 'Go',
    topics: ['monitoring', 'metrics', 'timeseries', 'alerting', 'promql', 'cncf-graduated'],
    updatedAt: new Date().toISOString(),
    createdAt: '2012-11-24T11:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'hall-of-fame'],
    isVerified: true,
    velocityScore: 90,
    velocityLabel: 'CLASSIC',
  },
  {
    id: 'grafana/grafana',
    fullName: 'grafana/grafana',
    name: 'grafana',
    owner: 'grafana',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/7199958?v=4',
    description: 'The open and composable observability and data visualization platform. Visualize metrics, logs, and traces from multiple sources.',
    url: 'https://github.com/grafana/grafana',
    stars: 65000,
    forks: 12000,
    openIssues: 2100,
    language: 'TypeScript',
    topics: ['visualization', 'dashboards', 'monitoring', 'observability', 'grafana', 'metrics'],
    updatedAt: new Date().toISOString(),
    createdAt: '2014-01-11T17:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'hall-of-fame'],
    isVerified: true,
    velocityScore: 92,
    velocityLabel: 'CLASSIC',
  },
  {
    id: 'aquasecurity/trivy',
    fullName: 'aquasecurity/trivy',
    name: 'trivy',
    owner: 'aquasecurity',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/12783832?v=4',
    description: 'Find vulnerabilities, misconfigurations, secrets, SBOM in containers, Kubernetes, code repositories, clouds and more.',
    url: 'https://github.com/aquasecurity/trivy',
    stars: 24500,
    forks: 2300,
    openIssues: 320,
    language: 'Go',
    topics: ['security', 'vulnerability-scanner', 'devsecops', 'container-security', 'sbom', 'iac-security'],
    updatedAt: new Date().toISOString(),
    createdAt: '2019-04-12T08:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'trending'],
    isVerified: true,
    velocityScore: 93,
    velocityLabel: 'HOT RISING',
  },
  {
    id: 'open-telemetry/opentelemetry-collector',
    fullName: 'open-telemetry/opentelemetry-collector',
    name: 'opentelemetry-collector',
    owner: 'open-telemetry',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/49258909?v=4',
    description: 'Vendor-agnostic collector to receive, process and export telemetry data (metrics, logs, traces).',
    url: 'https://github.com/open-telemetry/opentelemetry-collector',
    stars: 5400,
    forks: 1800,
    openIssues: 410,
    language: 'Go',
    topics: ['opentelemetry', 'observability', 'metrics', 'tracing', 'logs', 'cncf'],
    updatedAt: new Date().toISOString(),
    createdAt: '2019-06-01T12:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'trending'],
    isVerified: true,
    velocityScore: 92,
    velocityLabel: 'HOT RISING',
  },
  {
    id: 'falcosecurity/falco',
    fullName: 'falcosecurity/falco',
    name: 'falco',
    owner: 'falcosecurity',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/43970868?v=4',
    description: 'Cloud Native Runtime Security. Real-time threat detection for Linux, Kubernetes, containers, and cloud.',
    url: 'https://github.com/falcosecurity/falco',
    stars: 7200,
    forks: 890,
    openIssues: 190,
    language: 'C++',
    topics: ['security', 'ebpf', 'kubernetes', 'threat-detection', 'runtime-security', 'cncf-graduated'],
    updatedAt: new Date().toISOString(),
    createdAt: '2016-05-18T10:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra'],
    isVerified: true,
    velocityScore: 90,
    velocityLabel: 'TOP RATED',
  }
];
