import { RepoItem } from './types';

export const SEED_REPOSITORIES: RepoItem[] = [
  // --- DevOps Architecture & Best Practices ---
  {
    id: 'donnemartin/system-design-primer',
    fullName: 'donnemartin/system-design-primer',
    name: 'system-design-primer',
    owner: 'donnemartin',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/544330?v=4',
    description: 'Learn how to design large-scale systems. Prep for the system design interview. Includes Anki flashcards.',
    url: 'https://github.com/donnemartin/system-design-primer',
    stars: 285000,
    forks: 46000,
    openIssues: 380,
    language: 'Python',
    topics: ['system-design', 'architecture', 'interview-prep', 'scalability', 'distributed-systems', 'devops'],
    updatedAt: new Date().toISOString(),
    createdAt: '2017-02-26T16:15:28Z',
    category: 'architecture',
    categories: ['architecture', 'devops-infra', 'hall-of-fame'],
    isVerified: true,
    velocityScore: 98,
    velocityLabel: '💎 Battle-Tested',
    aiSummary: {
      tagline: 'The #1 definitive guide to large-scale distributed system design.',
      whyUseful: 'Provides battle-tested architecture patterns, scaling blueprints (CDN, load balancers, caching, microservices), and real-world system designs (Twitter, Pastebin, Uber).',
      targetAudience: ['DevOps Engineers', 'Solutions Architects', 'Staff Engineers'],
      topFeatures: ['Anki Flashcard decks', 'Step-by-step design exercises', 'Scalability trade-off comparisons']
    }
  },
  {
    id: 'kamranahmedse/developer-roadmap',
    fullName: 'kamranahmedse/developer-roadmap',
    name: 'developer-roadmap',
    owner: 'kamranahmedse',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/4921183?v=4',
    description: 'Interactive roadmaps, guides and other educational content to help developers grow in their career including DevOps, AI, and Cloud.',
    url: 'https://github.com/kamranahmedse/developer-roadmap',
    stars: 310000,
    forks: 39000,
    openIssues: 540,
    language: 'TypeScript',
    topics: ['devops-roadmap', 'ai-engineer', 'cloud-architecture', 'learning-paths', 'career-guide'],
    updatedAt: new Date().toISOString(),
    createdAt: '2017-03-15T13:45:00Z',
    category: 'architecture',
    categories: ['architecture', 'hall-of-fame'],
    isVerified: true,
    velocityScore: 95,
    velocityLabel: '💎 Battle-Tested',
    aiSummary: {
      tagline: 'Community-standard visual roadmaps for DevOps, AI Engineers, and Cloud practitioners.',
      whyUseful: 'Maps out modern skills, tooling prerequisites, and best practice pathways for engineers navigating rapid tech shifts.',
      targetAudience: ['DevOps Learners', 'AI Engineers', 'Tech Leads'],
      topFeatures: ['DevOps Roadmap', 'AI Engineer Path', 'Interactive skill assessments']
    }
  },
  {
    id: 'bregman-arie/devops-exercises',
    fullName: 'bregman-arie/devops-exercises',
    name: 'devops-exercises',
    owner: 'bregman-arie',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/10349437?v=4',
    description: 'Linux, Jenkins, AWS, SRE, Prometheus, Docker, Python, Ansible, Git, Kubernetes, Terraform, OpenStack, SQL, NoSQL, Questions and Answers.',
    url: 'https://github.com/bregman-arie/devops-exercises',
    stars: 65000,
    forks: 15500,
    openIssues: 120,
    language: 'Python',
    topics: ['devops', 'kubernetes', 'sre', 'ansible', 'terraform', 'interview-questions', 'docker'],
    updatedAt: new Date().toISOString(),
    createdAt: '2019-10-24T18:00:00Z',
    category: 'architecture',
    categories: ['architecture', 'devops-infra', 'hall-of-fame'],
    isVerified: true,
    velocityScore: 90,
    velocityLabel: '💎 Battle-Tested',
    aiSummary: {
      tagline: 'Comprehensive question bank and practical scenarios for DevOps & SRE.',
      whyUseful: 'Deep dive into practical troubleshooting, cloud infrastructure setups, and core DevOps domain mastery.',
      targetAudience: ['SREs', 'Cloud Engineers', 'Interview Candidates'],
      topFeatures: ['2,500+ technical exercises', 'Multi-tool coverage', 'Architecture Q&As']
    }
  },
  {
    id: 'kelseyhightower/kubernetes-the-hard-way',
    fullName: 'kelseyhightower/kubernetes-the-hard-way',
    name: 'kubernetes-the-hard-way',
    owner: 'kelseyhightower',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/1123322?v=4',
    description: 'Bootstrap Kubernetes the hard way on Google Cloud Platform or local VMs. No scripts, no magic.',
    url: 'https://github.com/kelseyhightower/kubernetes-the-hard-way',
    stars: 42000,
    forks: 14000,
    openIssues: 45,
    language: 'Shell',
    topics: ['kubernetes', 'cloud-native', 'security', 'tls', 'etcd', 'container-runtime', 'devops'],
    updatedAt: new Date().toISOString(),
    createdAt: '2016-08-01T20:00:00Z',
    category: 'architecture',
    categories: ['architecture', 'devops-infra'],
    isVerified: true,
    velocityScore: 88,
    velocityLabel: '💎 Battle-Tested',
    aiSummary: {
      tagline: 'The gold standard for understanding Kubernetes control plane internals from scratch.',
      whyUseful: 'Teaches TLS certificate management, etcd clustering, network overlays, and kubelet configuration without abstract magic.',
      targetAudience: ['Kubernetes Admins', 'Platform Engineers', 'DevOps Architects'],
      topFeatures: ['Manual control-plane setup', 'CA & TLS provisioning', 'Zero black-box tooling']
    }
  },
  {
    id: 'trimstray/the-book-of-secret-knowledge',
    fullName: 'trimstray/the-book-of-secret-knowledge',
    name: 'the-book-of-secret-knowledge',
    owner: 'trimstray',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/16100109?v=4',
    description: 'A collection of inspiring lists, manuals, cheatsheets, blogs, hacks, one-liners, cli/web tools and more.',
    url: 'https://github.com/trimstray/the-book-of-secret-knowledge',
    stars: 155000,
    forks: 17000,
    openIssues: 80,
    language: 'Shell',
    topics: ['devops', 'sysadmin', 'security', 'cheatsheet', 'linux', 'cloud', 'cli'],
    updatedAt: new Date().toISOString(),
    createdAt: '2018-08-11T12:00:00Z',
    category: 'architecture',
    categories: ['architecture', 'hall-of-fame'],
    isVerified: true,
    velocityScore: 92,
    velocityLabel: '💎 Battle-Tested',
    aiSummary: {
      tagline: 'The ultimate survival guide and CLI toolbox for DevOps and Security professionals.',
      whyUseful: 'Aggregates obscure one-liners, network debugging tricks, kernel tuning cheatsheets, and DevSecOps tools.',
      targetAudience: ['Sysadmins', 'DevSecOps', 'SREs'],
      topFeatures: ['CLI one-liners', 'Networking debugging guides', 'Security auditing tools']
    }
  },

  // --- Agentic AI & AI Engineers ---
  {
    id: 'ollama/ollama',
    fullName: 'ollama/ollama',
    name: 'ollama',
    owner: 'ollama',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/132925968?v=4',
    description: 'Get up and running with Llama 3.3, DeepSeek-R1, Mistral, Gemma 2, and other large language models locally.',
    url: 'https://github.com/ollama/ollama',
    stars: 128000,
    forks: 11000,
    openIssues: 950,
    language: 'Go',
    topics: ['llm', 'local-ai', 'deepseek', 'llama3', 'inference', 'go', 'agentic-ai'],
    updatedAt: new Date().toISOString(),
    createdAt: '2023-06-19T21:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'mlops', 'hall-of-fame', 'trending'],
    isVerified: true,
    velocityScore: 99,
    velocityLabel: '⚡ Explosive',
    aiSummary: {
      tagline: 'The standard runtime for running local LLMs with one command and OpenAI-compatible API.',
      whyUseful: 'Allows DevOps and developers to deploy, package, and orchestrate private local models with minimal resource footprint.',
      targetAudience: ['AI Engineers', 'DevOps Engineers', 'Local AI enthusiasts'],
      topFeatures: ['Modelfile configuration', 'OpenAI API compatible', 'GPU acceleration (NVIDIA/Metal/ROCm)']
    }
  },
  {
    id: 'vllm-project/vllm',
    fullName: 'vllm-project/vllm',
    name: 'vllm',
    owner: 'vllm-project',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/136070635?v=4',
    description: 'A high-throughput and memory-efficient inference and serving engine for LLMs.',
    url: 'https://github.com/vllm-project/vllm',
    stars: 39500,
    forks: 5800,
    openIssues: 1100,
    language: 'Python',
    topics: ['llm', 'inference', 'pagedattention', 'serving', 'distributed-serving', 'gpu'],
    updatedAt: new Date().toISOString(),
    createdAt: '2023-06-12T16:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'mlops', 'trending'],
    isVerified: true,
    velocityScore: 96,
    velocityLabel: '🔥 Hot Rising',
    aiSummary: {
      tagline: 'Industry-standard production LLM serving engine powered by PagedAttention.',
      whyUseful: 'Dramatically cuts GPU VRAM usage and skyrockets serving throughput (2x-4x vs naive servers) for enterprise AI pipelines.',
      targetAudience: ['MLOps Engineers', 'Cloud Infrastructure Leads', 'AI Platform Teams'],
      topFeatures: ['PagedAttention memory management', 'Continuous batching', 'Multi-GPU Tensor Parallelism']
    }
  },
  {
    id: 'crewAIInc/crewAI',
    fullName: 'crewAIInc/crewAI',
    name: 'crewAI',
    owner: 'crewAIInc',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/152917711?v=4',
    description: 'Framework for orchestrating role-playing, autonomous AI agents. By fostering collaborative intelligence.',
    url: 'https://github.com/crewAIInc/crewAI',
    stars: 26500,
    forks: 3400,
    openIssues: 260,
    language: 'Python',
    topics: ['ai-agents', 'autonomous-agents', 'crewai', 'multi-agent', 'llm-orchestration'],
    updatedAt: new Date().toISOString(),
    createdAt: '2023-11-20T10:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'trending'],
    isVerified: true,
    velocityScore: 94,
    velocityLabel: '🔥 Hot Rising',
    aiSummary: {
      tagline: 'Role-based multi-agent orchestration framework for autonomous task execution.',
      whyUseful: 'Enables teams of AI agents (e.g. Researcher + Coder + Reviewer) to collaborate sequentially or hierarchically.',
      targetAudience: ['AI Engineers', 'Automation Developers', 'Product Builders'],
      topFeatures: ['Role-playing agent crews', 'Delegation & hierarchical workflows', 'Tool integration']
    }
  },
  {
    id: 'microsoft/autogen',
    fullName: 'microsoft/autogen',
    name: 'autogen',
    owner: 'microsoft',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/6154722?v=4',
    description: 'A programming framework for agentic AI. Enabling next-gen LLM applications via multi-agent conversation.',
    url: 'https://github.com/microsoft/autogen',
    stars: 38000,
    forks: 5600,
    openIssues: 320,
    language: 'Python',
    topics: ['agentic-ai', 'multi-agent', 'conversational-ai', 'microsoft', 'code-execution'],
    updatedAt: new Date().toISOString(),
    createdAt: '2023-08-16T12:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'hall-of-fame'],
    isVerified: true,
    velocityScore: 91,
    velocityLabel: '💎 Battle-Tested',
    aiSummary: {
      tagline: 'Microsoft\'s customizable multi-agent framework with code execution sandboxes.',
      whyUseful: 'Builds self-correcting agent loops with automated code generation, sandboxed execution, and human-in-the-loop controls.',
      targetAudience: ['AI Researchers', 'Enterprise Developers', 'Platform Builders'],
      topFeatures: ['Multi-agent conversations', 'Docker sandboxed code runner', 'Human-in-the-loop']
    }
  },
  {
    id: 'langchain-ai/langchain',
    fullName: 'langchain-ai/langchain',
    name: 'langchain',
    owner: 'langchain-ai',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/126733545?v=4',
    description: '🦜🔗 Build context-aware reasoning applications with LCEL, LangGraph, and broad ecosystem connectors.',
    url: 'https://github.com/langchain-ai/langchain',
    stars: 98000,
    forks: 16000,
    openIssues: 1800,
    language: 'Python',
    topics: ['llm', 'rag', 'langchain', 'langgraph', 'agents', 'vector-search'],
    updatedAt: new Date().toISOString(),
    createdAt: '2022-10-25T14:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'mlops', 'hall-of-fame'],
    isVerified: true,
    velocityScore: 92,
    velocityLabel: '💎 Battle-Tested',
    aiSummary: {
      tagline: 'The most comprehensive application framework for building LLM and RAG pipelines.',
      whyUseful: 'Connects hundreds of LLM providers, vector databases, memory stores, and document loaders in a standardized interface.',
      targetAudience: ['AI Application Developers', 'Full-Stack Engineers'],
      topFeatures: ['LangGraph stateful agents', 'Rich document splitters/loaders', 'Hundreds of ecosystem integrations']
    }
  },
  {
    id: 'All-Hands-AI/OpenHands',
    fullName: 'All-Hands-AI/OpenHands',
    name: 'OpenHands',
    owner: 'All-Hands-AI',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/166662489?v=4',
    description: 'OpenHands: Code Less, Make More. An open-source autonomous AI software developer agent.',
    url: 'https://github.com/All-Hands-AI/OpenHands',
    stars: 44000,
    forks: 5200,
    openIssues: 410,
    language: 'Python',
    topics: ['autonomous-agent', 'swe-agent', 'code-generation', 'developer-tools', 'docker-sandbox'],
    updatedAt: new Date().toISOString(),
    createdAt: '2024-03-12T08:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'trending'],
    isVerified: true,
    velocityScore: 97,
    velocityLabel: '⚡ Explosive',
    aiSummary: {
      tagline: 'Open-source autonomous AI software engineer capable of modifying codebases and running tests.',
      whyUseful: 'Interacts with shells, browsers, and code editors inside a secure container to debug, build, and deploy software autonomously.',
      targetAudience: ['Developers', 'DevOps Automators', 'AI Researchers'],
      topFeatures: ['Browser & terminal interaction', 'Secure Docker sandbox', 'SWE-bench validated']
    }
  },

  // --- DevOps & Cloud-Native Infrastructure ---
  {
    id: 'kubernetes/kubernetes',
    fullName: 'kubernetes/kubernetes',
    name: 'kubernetes',
    owner: 'kubernetes',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/13629408?v=4',
    description: 'Production-Grade Container Scheduling and Management. The foundation of modern cloud-native systems.',
    url: 'https://github.com/kubernetes/kubernetes',
    stars: 112000,
    forks: 39000,
    openIssues: 2400,
    language: 'Go',
    topics: ['kubernetes', 'cloud-native', 'container-orchestration', 'cncf', 'go', 'devops'],
    updatedAt: new Date().toISOString(),
    createdAt: '2014-06-06T20:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'hall-of-fame'],
    isVerified: true,
    velocityScore: 94,
    velocityLabel: '💎 Battle-Tested',
    aiSummary: {
      tagline: 'The de facto global standard for container orchestration and cloud-native infrastructure.',
      whyUseful: 'Powers automated deployment, scaling, rolling updates, self-healing, and service discovery across multi-cloud environments.',
      targetAudience: ['Platform Engineers', 'DevOps Leads', 'SREs'],
      topFeatures: ['Declarative API', 'Extensible CRDs & Operators', 'Massive ecosystem']
    }
  },
  {
    id: 'argoproj/argo-cd',
    fullName: 'argoproj/argo-cd',
    name: 'argo-cd',
    owner: 'argoproj',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/30269780?v=4',
    description: 'Declarative, continuous delivery with a GitOps workflow for Kubernetes.',
    url: 'https://github.com/argoproj/argo-cd',
    stars: 18500,
    forks: 5400,
    openIssues: 1600,
    language: 'Go',
    topics: ['gitops', 'kubernetes', 'continuous-delivery', 'cncf-graduated', 'cloud-native'],
    updatedAt: new Date().toISOString(),
    createdAt: '2018-02-14T22:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'trending'],
    isVerified: true,
    velocityScore: 93,
    velocityLabel: '🔥 Hot Rising',
    aiSummary: {
      tagline: 'The leading declarative GitOps continuous delivery tool for Kubernetes.',
      whyUseful: 'Maintains single source of truth in Git, automated drift detection, rollbacks, and multi-cluster sync with a rich web UI.',
      targetAudience: ['DevOps Engineers', 'GitOps Practitioners', 'Release Engineers'],
      topFeatures: ['Automated drift correction', 'SSO & RBAC integration', 'Multi-cluster support']
    }
  },
  {
    id: 'hashicorp/terraform',
    fullName: 'hashicorp/terraform',
    name: 'terraform',
    owner: 'hashicorp',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/761456?v=4',
    description: 'Terraform enables you to safely and predictably create, change, and improve infrastructure. (IaC)',
    url: 'https://github.com/hashicorp/terraform',
    stars: 42500,
    forks: 9400,
    openIssues: 1500,
    language: 'Go',
    topics: ['iac', 'infrastructure-as-code', 'cloud', 'aws', 'gcp', 'azure', 'devops'],
    updatedAt: new Date().toISOString(),
    createdAt: '2014-05-13T16:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'hall-of-fame'],
    isVerified: true,
    velocityScore: 89,
    velocityLabel: '💎 Battle-Tested',
    aiSummary: {
      tagline: 'The pioneer declarative Infrastructure as Code (IaC) tool for multi-cloud provisioning.',
      whyUseful: 'Manages complete cloud lifecycles across AWS, GCP, Azure, and Kubernetes via declarative HCL configurations.',
      targetAudience: ['Cloud Engineers', 'DevOps Architects'],
      topFeatures: ['State management & locking', 'Execution plan previews', 'Thousands of cloud providers']
    }
  },
  {
    id: 'opentofu/opentofu',
    fullName: 'opentofu/opentofu',
    name: 'opentofu',
    owner: 'opentofu',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/144186526?v=4',
    description: 'OpenTofu is a truly open-source successor to Terraform managed by the Linux Foundation.',
    url: 'https://github.com/opentofu/opentofu',
    stars: 24000,
    forks: 1100,
    openIssues: 180,
    language: 'Go',
    topics: ['opentofu', 'terraform', 'iac', 'linux-foundation', 'open-source', 'cloud'],
    updatedAt: new Date().toISOString(),
    createdAt: '2023-08-25T14:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'trending'],
    isVerified: true,
    velocityScore: 95,
    velocityLabel: '🔥 Hot Rising',
    aiSummary: {
      tagline: 'Community-driven, open-source Linux Foundation alternative to Terraform.',
      whyUseful: 'Provides 100% drop-in compatibility with Terraform while adding state encryption, provider mocking, and open governance.',
      targetAudience: ['DevOps Teams', 'IaC Architects', 'Open-Source Purists'],
      topFeatures: ['State client-side encryption', 'Drop-in HCL compatibility', 'MPL-2.0 open-source license']
    }
  },
  {
    id: 'cilium/cilium',
    fullName: 'cilium/cilium',
    name: 'cilium',
    owner: 'cilium',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/17392688?v=4',
    description: 'eBPF-based Networking, Observability, and Security for Kubernetes and Cloud Native.',
    url: 'https://github.com/cilium/cilium',
    stars: 20500,
    forks: 3000,
    openIssues: 1200,
    language: 'Go',
    topics: ['ebpf', 'kubernetes', 'networking', 'security', 'observability', 'service-mesh'],
    updatedAt: new Date().toISOString(),
    createdAt: '2016-03-24T20:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'trending'],
    isVerified: true,
    velocityScore: 94,
    velocityLabel: '🔥 Hot Rising',
    aiSummary: {
      tagline: 'Next-gen eBPF-powered networking, service mesh, and security for Kubernetes.',
      whyUseful: 'Replaces slow iptables with lightning-fast kernel-level eBPF routing, transparent TLS, L7 network security, and Hubble observability.',
      targetAudience: ['Platform Engineers', 'DevSecOps', 'Network SREs'],
      topFeatures: ['Kernel eBPF data path', 'Sidecarless service mesh', 'Hubble visual network map']
    }
  },
  {
    id: 'crossplane/crossplane',
    fullName: 'crossplane/crossplane',
    name: 'crossplane',
    owner: 'crossplane',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/43970868?v=4',
    description: 'Cloud Native Control Planes. Turn Kubernetes into a universal control plane for any infrastructure.',
    url: 'https://github.com/crossplane/crossplane',
    stars: 10200,
    forks: 1200,
    openIssues: 380,
    language: 'Go',
    topics: ['control-plane', 'kubernetes', 'iac', 'cloud-native', 'cncf', 'internal-developer-platform'],
    updatedAt: new Date().toISOString(),
    createdAt: '2018-11-29T18:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra'],
    isVerified: true,
    velocityScore: 90,
    velocityLabel: '⭐ Top Rated',
    aiSummary: {
      tagline: 'Build internal developer platforms (IDP) with Kubernetes-native custom APIs.',
      whyUseful: 'Enables platform teams to compose high-level custom cloud resources (e.g. `MyCompanyDatabase`) mapped to AWS/GCP/Azure.',
      targetAudience: ['Internal Platform Teams', 'DevOps Architects'],
      topFeatures: ['Declarative compositions', 'CRD-based cloud provisioning', 'Continuous reconciliation']
    }
  },

  // --- MLOps & LLMOps ---
  {
    id: 'mlflow/mlflow',
    fullName: 'mlflow/mlflow',
    name: 'mlflow',
    owner: 'mlflow',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/38743126?v=4',
    description: 'Open source platform for the complete machine learning and GenAI lifecycle.',
    url: 'https://github.com/mlflow/mlflow',
    stars: 19800,
    forks: 4100,
    openIssues: 580,
    language: 'Python',
    topics: ['mlops', 'llmops', 'experiment-tracking', 'model-registry', 'genai', 'evaluation'],
    updatedAt: new Date().toISOString(),
    createdAt: '2018-05-30T22:00:00Z',
    category: 'mlops',
    categories: ['mlops', 'hall-of-fame'],
    isVerified: true,
    velocityScore: 91,
    velocityLabel: '💎 Battle-Tested',
    aiSummary: {
      tagline: 'Standard enterprise platform for ML & GenAI experiment tracking and model governance.',
      whyUseful: 'Tracks prompt engineering runs, fine-tuning hyperparameters, model artifacts, and deploys model endpoints seamlessly.',
      targetAudience: ['ML Engineers', 'Data Scientists', 'MLOps Architects'],
      topFeatures: ['GenAI prompt & trace evaluation', 'Model Registry', 'One-click deployment packaging']
    }
  },
  {
    id: 'qdrant/qdrant',
    fullName: 'qdrant/qdrant',
    name: 'qdrant',
    owner: 'qdrant',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/74640498?v=4',
    description: 'Qdrant - High-performance, massive-scale Vector Database and Vector Search Engine for the next generation of AI.',
    url: 'https://github.com/qdrant/qdrant',
    stars: 22000,
    forks: 1700,
    openIssues: 220,
    language: 'Rust',
    topics: ['vector-database', 'vector-search', 'rust', 'embeddings', 'rag', 'llmops'],
    updatedAt: new Date().toISOString(),
    createdAt: '2020-05-20T14:00:00Z',
    category: 'mlops',
    categories: ['mlops', 'trending'],
    isVerified: true,
    velocityScore: 96,
    velocityLabel: '🔥 Hot Rising',
    aiSummary: {
      tagline: 'Ultra-fast, Rust-powered vector database engineered for production RAG and semantic search.',
      whyUseful: 'Features payload filtering during search, quantization for 95% memory savings, and distributed replication.',
      targetAudience: ['MLOps Engineers', 'AI Backend Developers', 'Search Architects'],
      topFeatures: ['Rust high-performance core', 'Scalar & Product Quantization', 'Rich JSON payload filtering']
    }
  },
  {
    id: 'chroma-core/chroma',
    fullName: 'chroma-core/chroma',
    name: 'chroma',
    owner: 'chroma-core',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/104118928?v=4',
    description: 'the AI-native open-source embedding database.',
    url: 'https://github.com/chroma-core/chroma',
    stars: 17200,
    forks: 1600,
    openIssues: 450,
    language: 'Python',
    topics: ['vector-database', 'embeddings', 'rag', 'python', 'ai-native'],
    updatedAt: new Date().toISOString(),
    createdAt: '2022-10-18T18:00:00Z',
    category: 'mlops',
    categories: ['mlops'],
    isVerified: true,
    velocityScore: 89,
    velocityLabel: '⭐ Top Rated',
    aiSummary: {
      tagline: 'Developer-friendly embedded vector store for rapid prototyping and local RAG.',
      whyUseful: 'Zero-config setup in Python or JS, built-in embedding functions, and effortless LangChain/LlamaIndex pluggability.',
      targetAudience: ['AI Engineers', 'Fullstack Developers'],
      topFeatures: ['In-memory or disk persistence', 'Built-in embedding models', 'Single pip/npm install']
    }
  },
  {
    id: 'bentoml/BentoML',
    fullName: 'bentoml/BentoML',
    name: 'BentoML',
    owner: 'bentoml',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/48590623?v=4',
    description: 'The unified framework for building, shipping, and scaling AI applications and production models.',
    url: 'https://github.com/bentoml/BentoML',
    stars: 7600,
    forks: 850,
    openIssues: 140,
    language: 'Python',
    topics: ['model-serving', 'mlops', 'llmops', 'fastapi', 'distributed-serving', 'docker'],
    updatedAt: new Date().toISOString(),
    createdAt: '2019-03-27T08:00:00Z',
    category: 'mlops',
    categories: ['mlops'],
    isVerified: true,
    velocityScore: 87,
    velocityLabel: '⭐ Top Rated',
    aiSummary: {
      tagline: 'Production-ready model serving framework with auto-scaling and hardware optimization.',
      whyUseful: 'Standardizes packaging AI models into OCI container images with adaptive batching and multi-worker orchestration.',
      targetAudience: ['MLOps Engineers', 'AI Deployment Leads'],
      topFeatures: ['Adaptive batching engine', 'OpenLLM integration', 'BentoCloud serverless deployment']
    }
  },
  {
    id: 'Arize-ai/phoenix',
    fullName: 'Arize-ai/phoenix',
    name: 'phoenix',
    owner: 'Arize-ai',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/59938069?v=4',
    description: 'AI Observability & Evaluation. OpenTelemetry-based tracing, evals, and prompt analytics for LLM applications.',
    url: 'https://github.com/Arize-ai/phoenix',
    stars: 5800,
    forks: 520,
    openIssues: 90,
    language: 'Python',
    topics: ['llm-observability', 'opentelemetry', 'evals', 'rag-evaluation', 'tracing', 'llmops'],
    updatedAt: new Date().toISOString(),
    createdAt: '2023-01-20T18:00:00Z',
    category: 'mlops',
    categories: ['mlops', 'trending'],
    isVerified: true,
    velocityScore: 92,
    velocityLabel: '🔥 Hot Rising',
    aiSummary: {
      tagline: 'OpenTelemetry-native observability and automated evaluation for LLM applications.',
      whyUseful: 'Traces multi-step agent chains, diagnoses hallucination rates, inspects RAG retrieval quality, and benchmarks prompt variants.',
      targetAudience: ['AI Engineers', 'LLMOps Teams', 'SREs'],
      topFeatures: ['OpenTelemetry tracing', 'Evals for RAG accuracy', 'Latency and token cost breakdown']
    }
  },

  // --- Observability & DevSecOps ---
  {
    id: 'prometheus/prometheus',
    fullName: 'prometheus/prometheus',
    name: 'prometheus',
    owner: 'prometheus',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/3380462?v=4',
    description: 'The Prometheus monitoring system and time series database. CNCF graduated foundation of observability.',
    url: 'https://github.com/prometheus/prometheus',
    stars: 57000,
    forks: 9200,
    openIssues: 800,
    language: 'Go',
    topics: ['monitoring', 'metrics', 'timeseries', 'alerting', 'promql', 'cncf-graduated'],
    updatedAt: new Date().toISOString(),
    createdAt: '2012-11-24T11:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'hall-of-fame'],
    isVerified: true,
    velocityScore: 90,
    velocityLabel: '💎 Battle-Tested',
    aiSummary: {
      tagline: 'The industry-standard metric collection and alerting engine with PromQL.',
      whyUseful: 'Pulls metrics from thousands of targets via multidimensional data model, offering powerful PromQL querying and alert management.',
      targetAudience: ['SREs', 'DevOps Engineers', 'Platform Architects'],
      topFeatures: ['Multi-dimensional metrics', 'PromQL querying language', 'Service discovery integrations']
    }
  },
  {
    id: 'grafana/grafana',
    fullName: 'grafana/grafana',
    name: 'grafana',
    owner: 'grafana',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/7199958?v=4',
    description: 'The open and composable observability and data visualization platform. Visualize metrics, logs, and traces from multiple sources.',
    url: 'https://github.com/grafana/grafana',
    stars: 65000,
    forks: 12000,
    openIssues: 2100,
    language: 'TypeScript',
    topics: ['visualization', 'dashboards', 'monitoring', 'observability', 'grafana', 'metrics'],
    updatedAt: new Date().toISOString(),
    createdAt: '2014-01-11T17:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'hall-of-fame'],
    isVerified: true,
    velocityScore: 92,
    velocityLabel: '💎 Battle-Tested',
    aiSummary: {
      tagline: 'The world\'s most popular visualization dashboard for logs, metrics, and traces.',
      whyUseful: 'Unifies data from Prometheus, Loki, Jaeger, Elasticsearch, and CloudWatch into rich, actionable real-time dashboards.',
      targetAudience: ['DevOps Engineers', 'SREs', 'Engineering Managers'],
      topFeatures: ['Composable dashboard panels', 'Unified alerting', '100+ datasource connectors']
    }
  },
  {
    id: 'aquasecurity/trivy',
    fullName: 'aquasecurity/trivy',
    name: 'trivy',
    owner: 'aquasecurity',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/12783832?v=4',
    description: 'Find vulnerabilities, misconfigurations, secrets, SBOM in containers, Kubernetes, code repositories, clouds and more.',
    url: 'https://github.com/aquasecurity/trivy',
    stars: 24500,
    forks: 2300,
    openIssues: 320,
    language: 'Go',
    topics: ['security', 'vulnerability-scanner', 'devsecops', 'container-security', 'sbom', 'iac-security'],
    updatedAt: new Date().toISOString(),
    createdAt: '2019-04-12T08:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'trending'],
    isVerified: true,
    velocityScore: 93,
    velocityLabel: '🔥 Hot Rising',
    aiSummary: {
      tagline: 'All-in-one DevSecOps scanner for container images, Git repos, IaC, and Kubernetes.',
      whyUseful: 'Integrates easily into CI/CD pipelines to block vulnerable dependencies, misconfigured Terraform files, and leaked credentials.',
      targetAudience: ['DevSecOps Engineers', 'Security Analysts', 'CI/CD Pipeline Builders'],
      topFeatures: ['Container & OS package scanning', 'IaC misconfiguration checks', 'SBOM generation']
    }
  }
];
