import { RepoItem } from './types';

export const SEED_REPOSITORIES: RepoItem[] = [
  // ==========================================
  // 1. VIRAL PHENOMENA & BREAKOUT AI AGENTS (2025-2026)
  // ==========================================
  {
    id: 'OpenClaw/openclaw',
    fullName: 'OpenClaw/openclaw',
    name: 'openclaw',
    owner: 'OpenClaw',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/190000001?v=4',
    description: 'Local-first personal AI assistant connecting LLMs to 50+ integrations (Slack, WhatsApp, GitHub, shell). Privacy-focused autonomous agent that runs entirely on your machine.',
    url: 'https://github.com/OpenClaw/openclaw',
    stars: 346000,
    forks: 28000,
    openIssues: 840,
    language: 'TypeScript',
    topics: ['local-ai', 'ai-agent', 'personal-ai', 'privacy', 'local-llm', 'automation', 'mcp'],
    updatedAt: new Date().toISOString(),
    createdAt: '2025-10-01T08:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'trending'],
    isVerified: true,
    velocityScore: 100,
    velocityLabel: 'EXPLOSIVE',
    growthDeltaText: '346k stars • #1 Viral Repo of 2026',
    socialSignals: { githubTrending: 'daily', hnTopScore: 850, devtoTopReactions: 1200 },
  },
  {
    id: 'PrimeIntellect-ai/prime-agent',
    fullName: 'PrimeIntellect-ai/prime-agent',
    name: 'prime-agent',
    owner: 'PrimeIntellect-ai',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/190000002?v=4',
    description: 'Open-source self-improving Recursive Language Model (RLM) agent for coding and long-horizon autonomous tasks. Hit GitHub Trending #1 with 2,200+ stars/day.',
    url: 'https://github.com/PrimeIntellect-ai/prime-agent',
    stars: 8900,
    forks: 720,
    openIssues: 42,
    language: 'Python',
    topics: ['rlm', 'self-improving-agent', 'agentic-ai', 'coding-agent', 'autonomous-agent'],
    updatedAt: new Date().toISOString(),
    createdAt: '2025-07-15T10:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'trending'],
    isVerified: true,
    velocityScore: 99,
    velocityLabel: 'EXPLOSIVE',
    growthDeltaText: '+2,200 stars/day • Trending Breakout',
    socialSignals: { githubTrending: 'daily', hnTopScore: 420 },
  },
  {
    id: 'perplexity-ai/bumblebee',
    fullName: 'perplexity-ai/bumblebee',
    name: 'bumblebee',
    owner: 'perplexity-ai',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/110818060?v=4',
    description: 'Read-only AI supply-chain security scanner by Perplexity AI. Inventories developer endpoints: packages, MCP servers, editor extensions, and AI tool configs.',
    url: 'https://github.com/perplexity-ai/bumblebee',
    stars: 6400,
    forks: 410,
    openIssues: 28,
    language: 'Go',
    topics: ['supply-chain', 'appsec', 'devsecops', 'sbom', 'ai-security', 'mcp-security'],
    updatedAt: new Date().toISOString(),
    createdAt: '2026-05-10T14:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'agentic-ai', 'trending'],
    isVerified: true,
    velocityScore: 97,
    velocityLabel: 'HOT RISING',
    growthDeltaText: '+85 stars/day • Supply Chain Scanner',
    socialSignals: { hnTopScore: 280, devtoTopReactions: 60 },
  },
  {
    id: 'mastra-ai/mastra',
    fullName: 'mastra-ai/mastra',
    name: 'mastra',
    owner: 'mastra-ai',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/190000003?v=4',
    description: 'TypeScript-first production agent framework with strong ecosystem support, tool calling, memory, and agent-to-agent communication built-in.',
    url: 'https://github.com/mastra-ai/mastra',
    stars: 12400,
    forks: 1100,
    openIssues: 64,
    language: 'TypeScript',
    topics: ['agent-framework', 'typescript', 'ai-agent', 'tool-calling', 'production-ai'],
    updatedAt: new Date().toISOString(),
    createdAt: '2025-09-01T09:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'trending'],
    isVerified: true,
    velocityScore: 96,
    velocityLabel: 'HOT RISING',
    growthDeltaText: '+120 stars/day • TypeScript Agent Framework',
    socialSignals: { githubTrending: 'weekly', hnTopScore: 190 },
  },
  {
    id: 'usestrix/strix',
    fullName: 'usestrix/strix',
    name: 'strix',
    owner: 'usestrix',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/190800000?v=4',
    description: 'Open-source autonomous AI penetration testing agent. Multi-agent framework to proactively find, validate, and fix security vulnerabilities in CI/CD.',
    url: 'https://github.com/usestrix/strix',
    stars: 58400,
    forks: 5100,
    openIssues: 120,
    language: 'Python',
    topics: ['ai-agent', 'penetration-testing', 'security', 'devsecops', 'red-teaming', 'vulnerability-scanner'],
    updatedAt: new Date().toISOString(),
    createdAt: '2024-06-15T10:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'devops-infra', 'trending'],
    isVerified: true,
    velocityScore: 98,
    velocityLabel: 'ESTABLISHED',
    hasBigUpdate: true,
    growthDeltaText: '58.4k stars • AI Penetration Testing Agent',
    socialSignals: { hnTopScore: 340, devtoTopReactions: 80 },
  },
  {
    id: 'Tencent/AI-Infra-Guard',
    fullName: 'Tencent/AI-Infra-Guard',
    name: 'AI-Infra-Guard',
    owner: 'Tencent',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/18460505?v=4',
    description: 'Tencent Zhuque Lab Full-Stack AI Red Teaming platform: Agent Scan, Skills Scan, MCP Scan, and AI Infrastructure security scanner.',
    url: 'https://github.com/Tencent/AI-Infra-Guard',
    stars: 3900,
    forks: 480,
    openIssues: 18,
    language: 'Python',
    topics: ['ai-security', 'red-teaming', 'agent-security', 'mcp-scan', 'skills-scan', 'devsecops', 'jailbreak'],
    updatedAt: new Date().toISOString(),
    createdAt: '2025-01-10T08:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'devops-infra', 'trending'],
    isVerified: true,
    velocityScore: 99,
    velocityLabel: 'EXPLOSIVE',
    growthDeltaText: 'Viral on Tech Community • Red Teaming',
    socialSignals: { githubTrending: 'daily', devtoMentions: 1 },
  },
  {
    id: 'All-Hands-AI/OpenHands',
    fullName: 'All-Hands-AI/OpenHands',
    name: 'OpenHands',
    owner: 'All-Hands-AI',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/165997619?v=4',
    description: 'OpenHands (formerly OpenDevin): An open-source autonomous AI software developer capable of creating websites, fixing bugs, and executing terminal tasks.',
    url: 'https://github.com/All-Hands-AI/OpenHands',
    stars: 48500,
    forks: 5900,
    openIssues: 320,
    language: 'Python',
    topics: ['ai-agent', 'software-engineering', 'autonomous-agent', 'coding-agent', 'opendevin'],
    updatedAt: new Date().toISOString(),
    createdAt: '2024-03-12T00:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'trending'],
    isVerified: true,
    velocityScore: 97,
    velocityLabel: 'HOT RISING',
    growthDeltaText: '+95 stars/day • Premier Open Coding Agent',
    socialSignals: { githubTrending: 'weekly', hnTopScore: 520 },
  },
  {
    id: 'SWE-agent/SWE-agent',
    fullName: 'SWE-agent/SWE-agent',
    name: 'SWE-agent',
    owner: 'SWE-agent',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/166014407?v=4',
    description: 'SWE-agent turns LMs into software engineering agents that can fix bugs and issues in real GitHub repositories automatically.',
    url: 'https://github.com/SWE-agent/SWE-agent',
    stars: 16800,
    forks: 1800,
    openIssues: 85,
    language: 'Python',
    topics: ['swe-bench', 'ai-agent', 'automated-code-repair', 'llm-agents'],
    updatedAt: new Date().toISOString(),
    createdAt: '2024-04-01T00:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'trending'],
    isVerified: true,
    velocityScore: 94,
    velocityLabel: 'HOT RISING',
    growthDeltaText: 'Princeton AI Lab Software Engineering Agent',
  },
  {
    id: 'cline/cline',
    fullName: 'cline/cline',
    name: 'cline',
    owner: 'cline',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/178559092?v=4',
    description: 'Autonomous coding agent right in your IDE. Creates/edits files, executes terminal commands, and analyzes browser errors with MCP tool support.',
    url: 'https://github.com/cline/cline',
    stars: 31200,
    forks: 3400,
    openIssues: 410,
    language: 'TypeScript',
    topics: ['vscode-extension', 'ai-agent', 'mcp', 'autonomous-coding', 'copilot'],
    updatedAt: new Date().toISOString(),
    createdAt: '2024-07-20T00:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'trending'],
    isVerified: true,
    velocityScore: 98,
    velocityLabel: 'EXPLOSIVE',
    growthDeltaText: '+180 stars/day • Top IDE Coding Agent',
    socialSignals: { githubTrending: 'daily', hnTopScore: 310 },
  },
  {
    id: 'RooVetGit/Roo-Cline',
    fullName: 'RooVetGit/Roo-Cline',
    name: 'Roo-Cline',
    owner: 'RooVetGit',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/1051509?v=4',
    description: 'Autonomous AI assistant that can code, run commands, use browser tools, and integrate with MCP servers. Highly customized power-user fork.',
    url: 'https://github.com/RooVetGit/Roo-Cline',
    stars: 14500,
    forks: 1600,
    openIssues: 190,
    language: 'TypeScript',
    topics: ['ai-agent', 'coding-assistant', 'vscode-extension', 'mcp'],
    updatedAt: new Date().toISOString(),
    createdAt: '2024-11-01T00:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'trending'],
    isVerified: true,
    velocityScore: 96,
    velocityLabel: 'HOT RISING',
    growthDeltaText: '+75 stars/day • Roo Code IDE Agent',
  },
  {
    id: 'paul-gauthier/aider',
    fullName: 'paul-gauthier/aider',
    name: 'aider',
    owner: 'paul-gauthier',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/23840?v=4',
    description: 'aider is AI pair programming in your terminal. Edit code in your local git repository with Claude 3.5 Sonnet, GPT-4o, and local models.',
    url: 'https://github.com/paul-gauthier/aider',
    stars: 28400,
    forks: 2600,
    openIssues: 140,
    language: 'Python',
    topics: ['cli', 'terminal', 'ai-pair-programmer', 'git-workflow', 'coding-assistant'],
    updatedAt: new Date().toISOString(),
    createdAt: '2023-05-20T00:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'trending'],
    isVerified: true,
    velocityScore: 95,
    velocityLabel: 'HOT RISING',
    growthDeltaText: 'Top Terminal AI Pair Programmer',
    socialSignals: { hnTopScore: 480 },
  },
  {
    id: 'crewAIInc/crewAI',
    fullName: 'crewAIInc/crewAI',
    name: 'crewAI',
    owner: 'crewAIInc',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/152342080?v=4',
    description: 'Framework for orchestrating role-playing, autonomous AI agents. By fostering collaborative intelligence, CrewAI empowers agents to tackle complex tasks.',
    url: 'https://github.com/crewAIInc/crewAI',
    stars: 27800,
    forks: 3900,
    openIssues: 260,
    language: 'Python',
    topics: ['multi-agent', 'agent-orchestration', 'role-playing-agents', 'llm-framework'],
    updatedAt: new Date().toISOString(),
    createdAt: '2023-11-20T00:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'trending'],
    isVerified: true,
    velocityScore: 96,
    velocityLabel: 'HOT RISING',
    growthDeltaText: '+80 stars/day • Multi-Agent Orchestration',
  },
  {
    id: 'langchain-ai/langgraph',
    fullName: 'langchain-ai/langgraph',
    name: 'langgraph',
    owner: 'langchain-ai',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/126733545?v=4',
    description: 'Build resilient language agents as graphs with cyclical execution, human-in-the-loop, multi-agent communication, and persistent state.',
    url: 'https://github.com/langchain-ai/langgraph',
    stars: 12900,
    forks: 1800,
    openIssues: 110,
    language: 'Python',
    topics: ['agentic-framework', 'state-machine', 'multi-agent', 'langchain', 'production-ai'],
    updatedAt: new Date().toISOString(),
    createdAt: '2024-01-15T00:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'trending'],
    isVerified: true,
    velocityScore: 97,
    velocityLabel: 'HOT RISING',
    growthDeltaText: '+65 stars/day • Industry Standard Agent Graphs',
  },
  {
    id: 'langgenius/dify',
    fullName: 'langgenius/dify',
    name: 'dify',
    owner: 'langgenius',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/128362670?v=4',
    description: 'Dify is an open-source LLM app development platform. Orchestrates Agentic AI workflows, RAG pipelines, and model evaluation with an intuitive visual canvas.',
    url: 'https://github.com/langgenius/dify',
    stars: 68500,
    forks: 9800,
    openIssues: 420,
    language: 'TypeScript',
    topics: ['llm-platform', 'agentic-workflow', 'rag', 'visual-canvas', 'enterprise-ai'],
    updatedAt: new Date().toISOString(),
    createdAt: '2023-03-01T00:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'trending'],
    isVerified: true,
    velocityScore: 98,
    velocityLabel: 'EXPLOSIVE',
    growthDeltaText: '68.5k stars • Leading Visual Agent Builder',
    socialSignals: { githubTrending: 'weekly' },
  },
  {
    id: 'mem0ai/mem0',
    fullName: 'mem0ai/mem0',
    name: 'mem0',
    owner: 'mem0ai',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/174411138?v=4',
    description: 'The memory layer for personalized AI agents and assistants. Retains user preferences and historical interaction context across sessions.',
    url: 'https://github.com/mem0ai/mem0',
    stars: 26200,
    forks: 2400,
    openIssues: 110,
    language: 'Python',
    topics: ['ai-memory', 'long-term-memory', 'agent-context', 'personalization', 'rag'],
    updatedAt: new Date().toISOString(),
    createdAt: '2024-06-25T00:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'trending'],
    isVerified: true,
    velocityScore: 98,
    velocityLabel: 'EXPLOSIVE',
    growthDeltaText: '+110 stars/day • Universal AI Memory Layer',
    socialSignals: { githubTrending: 'daily', hnTopScore: 290 },
  },
  {
    id: 'letta-ai/letta',
    fullName: 'letta-ai/letta',
    name: 'letta',
    owner: 'letta-ai',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/150774205?v=4',
    description: 'Letta (formerly MemGPT): State machine framework for building stateful LLM agents with self-editing persistent memory.',
    url: 'https://github.com/letta-ai/letta',
    stars: 15400,
    forks: 1800,
    openIssues: 85,
    language: 'Python',
    topics: ['memgpt', 'persistent-memory', 'stateful-agents', 'llm-operating-system'],
    updatedAt: new Date().toISOString(),
    createdAt: '2023-10-10T00:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'trending'],
    isVerified: true,
    velocityScore: 93,
    velocityLabel: 'HOT RISING',
    growthDeltaText: 'Berkeley Stateful AI Agent Engine',
  },
  {
    id: 'obra/superpowers',
    fullName: 'obra/superpowers',
    name: 'superpowers',
    owner: 'obra',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/216?v=4',
    description: 'An agentic skills framework and software development methodology for coding agents (Claude Code, Cursor, Antigravity, Codex). Enforces TDD, brainstorming, and planning.',
    url: 'https://github.com/obra/superpowers',
    stars: 5200,
    forks: 410,
    openIssues: 18,
    language: 'Markdown',
    topics: ['agent-skills', 'superpowers', 'claude-code', 'tdd', 'software-engineering-methodology'],
    updatedAt: new Date().toISOString(),
    createdAt: '2025-02-01T00:00:00Z',
    category: 'agentic-ai',
    categories: ['agentic-ai', 'trending'],
    isVerified: true,
    velocityScore: 99,
    velocityLabel: 'EXPLOSIVE',
    growthDeltaText: 'Viral Coding Agent Methodology',
    socialSignals: { githubTrending: 'daily', hnTopScore: 380 },
  },

  // ==========================================
  // 2. AI SERVING, LOCAL MODELS & LLMOPS
  // ==========================================
  {
    id: 'ollama/ollama',
    fullName: 'ollama/ollama',
    name: 'ollama',
    owner: 'ollama',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/132925495?v=4',
    description: 'Get up and running with Llama 3.3, DeepSeek-R1, Mistral, Qwen, and other large language models locally on macOS, Linux, and Windows.',
    url: 'https://github.com/ollama/ollama',
    stars: 128000,
    forks: 11200,
    openIssues: 920,
    language: 'Go',
    topics: ['local-ai', 'llama', 'deepseek', 'model-serving', 'inference', 'cli'],
    updatedAt: new Date().toISOString(),
    createdAt: '2023-06-20T00:00:00Z',
    category: 'mlops',
    categories: ['mlops', 'agentic-ai', 'trending'],
    isVerified: true,
    velocityScore: 99,
    velocityLabel: 'ESTABLISHED',
    hasBigUpdate: true,
    growthDeltaText: '128k stars • De-facto Standard Local AI Runtime',
    socialSignals: { githubTrending: 'weekly' },
  },
  {
    id: 'vllm-project/vllm',
    fullName: 'vllm-project/vllm',
    name: 'vllm',
    owner: 'vllm-project',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/137684570?v=4',
    description: 'A high-throughput and memory-efficient inference and serving engine for LLMs. Features PagedAttention for 10x-24x higher serving throughput.',
    url: 'https://github.com/vllm-project/vllm',
    stars: 38500,
    forks: 5800,
    openIssues: 680,
    language: 'Python',
    topics: ['llm-inference', 'paged-attention', 'gpu-serving', 'high-throughput', 'mlops'],
    updatedAt: new Date().toISOString(),
    createdAt: '2023-06-10T00:00:00Z',
    category: 'mlops',
    categories: ['mlops', 'devops-infra', 'trending'],
    isVerified: true,
    velocityScore: 98,
    velocityLabel: 'HOT RISING',
    growthDeltaText: '+70 stars/day • Premier Production LLM Engine',
    socialSignals: { githubTrending: 'weekly', devtoTopReactions: 95 },
  },
  {
    id: 'sgl-project/sglang',
    fullName: 'sgl-project/sglang',
    name: 'sglang',
    owner: 'sgl-project',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/161048689?v=4',
    description: 'SGLang is a fast serving framework for large language models and vision-language models. Features RadixAttention and structured generation acceleration.',
    url: 'https://github.com/sgl-project/sglang',
    stars: 11400,
    forks: 1200,
    openIssues: 210,
    language: 'Python',
    topics: ['radix-attention', 'llm-serving', 'fast-inference', 'deepseek-serving'],
    updatedAt: new Date().toISOString(),
    createdAt: '2024-01-10T00:00:00Z',
    category: 'mlops',
    categories: ['mlops', 'trending'],
    isVerified: true,
    velocityScore: 98,
    velocityLabel: 'EXPLOSIVE',
    growthDeltaText: '+95 stars/day • DeepSeek Serving Benchmark Leader',
    socialSignals: { githubTrending: 'daily', hnTopScore: 310 },
  },
  {
    id: 'open-webui/open-webui',
    fullName: 'open-webui/open-webui',
    name: 'open-webui',
    owner: 'open-webui',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/156767516?v=4',
    description: 'User-friendly AI interface (Supports Ollama, OpenAI API, Anthropic, Gemini, pipelines). Full self-hosted ChatGPT alternative with RAG and voice input.',
    url: 'https://github.com/open-webui/open-webui',
    stars: 76500,
    forks: 8900,
    openIssues: 540,
    language: 'JavaScript',
    topics: ['webui', 'ollama', 'chatgpt-alternative', 'self-hosted', 'rag-ui'],
    updatedAt: new Date().toISOString(),
    createdAt: '2023-10-15T00:00:00Z',
    category: 'mlops',
    categories: ['mlops', 'agentic-ai', 'trending'],
    isVerified: true,
    velocityScore: 98,
    velocityLabel: 'EXPLOSIVE',
    growthDeltaText: '76.5k stars • #1 Self-Hosted AI Web Interface',
    socialSignals: { githubTrending: 'daily' },
  },
  {
    id: 'ggerganov/llama.cpp',
    fullName: 'ggerganov/llama.cpp',
    name: 'llama.cpp',
    owner: 'ggerganov',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/1991296?v=4',
    description: 'LLM inference in C/C++ with minimal dependencies, optimized for Apple Silicon, CPU AVX-512, and consumer GPUs.',
    url: 'https://github.com/ggerganov/llama.cpp',
    stars: 74200,
    forks: 10400,
    openIssues: 680,
    language: 'C++',
    topics: ['c-plus-plus', 'quantization', 'gguf', 'edge-inference', 'metal', 'cuda'],
    updatedAt: new Date().toISOString(),
    createdAt: '2023-03-10T00:00:00Z',
    category: 'mlops',
    categories: ['mlops', 'architecture'],
    isVerified: true,
    velocityScore: 96,
    velocityLabel: 'ESTABLISHED',
    growthDeltaText: 'Foundation of Modern Local AI (GGUF)',
  },
  {
    id: 'unslothai/unsloth',
    fullName: 'unslothai/unsloth',
    name: 'unsloth',
    owner: 'unslothai',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/144275037?v=4',
    description: 'Finetune Llama 3.3, Mistral, Phi-4, and DeepSeek-R1 2x-5x faster with 70% less VRAM. Open-source memory-efficient fine-tuning kernels.',
    url: 'https://github.com/unslothai/unsloth',
    stars: 25900,
    forks: 2100,
    openIssues: 180,
    language: 'Python',
    topics: ['fine-tuning', 'lora', 'qlora', 'vram-optimization', 'deepseek-r1-finetuning'],
    updatedAt: new Date().toISOString(),
    createdAt: '2023-12-01T00:00:00Z',
    category: 'mlops',
    categories: ['mlops', 'trending'],
    isVerified: true,
    velocityScore: 97,
    velocityLabel: 'HOT RISING',
    growthDeltaText: '+80 stars/day • 5x Faster LLM Finetuning',
    socialSignals: { githubTrending: 'weekly' },
  },
  {
    id: 'hiyouga/LLaMA-Factory',
    fullName: 'hiyouga/LLaMA-Factory',
    name: 'LLaMA-Factory',
    owner: 'hiyouga',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/29624505?v=4',
    description: 'Unified efficient fine-tuning of 100+ LLMs & VLMs (Llama, Qwen, DeepSeek, Mistral) via web UI and CLI with DPO, PPO, and SFT support.',
    url: 'https://github.com/hiyouga/LLaMA-Factory',
    stars: 41200,
    forks: 5600,
    openIssues: 290,
    language: 'Python',
    topics: ['dpo', 'sft', 'rlhf', 'unified-finetuning', 'webui-training'],
    updatedAt: new Date().toISOString(),
    createdAt: '2023-05-15T00:00:00Z',
    category: 'mlops',
    categories: ['mlops', 'trending'],
    isVerified: true,
    velocityScore: 97,
    velocityLabel: 'HOT RISING',
    growthDeltaText: '41.2k stars • Universal Fine-Tuning Suite',
  },
  {
    id: 'qdrant/qdrant',
    fullName: 'qdrant/qdrant',
    name: 'qdrant',
    owner: 'qdrant',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/74384918?v=4',
    description: 'Qdrant - High-performance, massive-scale Vector Database and Vector Search Engine written in Rust with payload filtering support.',
    url: 'https://github.com/qdrant/qdrant',
    stars: 23400,
    forks: 1800,
    openIssues: 95,
    language: 'Rust',
    topics: ['vector-database', 'rust', 'similarity-search', 'rag-engine', 'embeddings'],
    updatedAt: new Date().toISOString(),
    createdAt: '2021-05-20T00:00:00Z',
    category: 'mlops',
    categories: ['mlops', 'devops-infra'],
    isVerified: true,
    velocityScore: 95,
    velocityLabel: 'HOT RISING',
    growthDeltaText: 'Industry Leading Rust Vector Database',
  },
  {
    id: 'chroma-core/chroma',
    fullName: 'chroma-core/chroma',
    name: 'chroma',
    owner: 'chroma-core',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/105747683?v=4',
    description: 'Chroma - the AI-native open-source embedding database. Designed for developer productivity and seamless local/cloud vector search.',
    url: 'https://github.com/chroma-core/chroma',
    stars: 19800,
    forks: 1700,
    openIssues: 180,
    language: 'Python',
    topics: ['vector-store', 'ai-native', 'embeddings', 'rag', 'python'],
    updatedAt: new Date().toISOString(),
    createdAt: '2022-10-10T00:00:00Z',
    category: 'mlops',
    categories: ['mlops', 'agentic-ai'],
    isVerified: true,
    velocityScore: 93,
    velocityLabel: 'HOT RISING',
    growthDeltaText: 'Default Vector Database for Python AI Stack',
  },
  {
    id: 'Arize-ai/phoenix',
    fullName: 'Arize-ai/phoenix',
    name: 'phoenix',
    owner: 'Arize-ai',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/61821035?v=4',
    description: 'AI Observability & Evaluation Platform: LLM tracing, evaluations, RAG performance analysis, and agent step-by-step debugging.',
    url: 'https://github.com/Arize-ai/phoenix',
    stars: 6400,
    forks: 580,
    openIssues: 45,
    language: 'TypeScript',
    topics: ['ai-observability', 'llm-tracing', 'rag-evaluation', 'agent-debugging', 'opentelemetry'],
    updatedAt: new Date().toISOString(),
    createdAt: '2023-08-01T00:00:00Z',
    category: 'mlops',
    categories: ['mlops', 'devops-infra', 'trending'],
    isVerified: true,
    velocityScore: 94,
    velocityLabel: 'HOT RISING',
    growthDeltaText: '+45 stars/day • AI Tracing & Eval Platform',
  },
  {
    id: 'langfuse/langfuse',
    fullName: 'langfuse/langfuse',
    name: 'langfuse',
    owner: 'langfuse',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/132454508?v=4',
    description: 'Open source LLM engineering platform: Observability, metrics, evaluations, prompt management and playground for teams.',
    url: 'https://github.com/langfuse/langfuse',
    stars: 9200,
    forks: 820,
    openIssues: 75,
    language: 'TypeScript',
    topics: ['llm-engineering', 'prompt-management', 'tracing', 'evaluations', 'observability'],
    updatedAt: new Date().toISOString(),
    createdAt: '2023-06-01T00:00:00Z',
    category: 'mlops',
    categories: ['mlops', 'trending'],
    isVerified: true,
    velocityScore: 96,
    velocityLabel: 'HOT RISING',
    growthDeltaText: '+60 stars/day • Premier Open LLM Observability',
  },
  {
    id: 'mlflow/mlflow',
    fullName: 'mlflow/mlflow',
    name: 'mlflow',
    owner: 'mlflow',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/38890980?v=4',
    description: 'Open source platform for the machine learning lifecycle: experiment tracking, model registry, deployment, and LLM evaluation.',
    url: 'https://github.com/mlflow/mlflow',
    stars: 19800,
    forks: 4100,
    openIssues: 580,
    language: 'Python',
    topics: ['experiment-tracking', 'model-registry', 'ml-lifecycle', 'production-ml'],
    updatedAt: new Date().toISOString(),
    createdAt: '2018-06-05T00:00:00Z',
    category: 'mlops',
    categories: ['mlops', 'devops-infra'],
    isVerified: true,
    velocityScore: 88,
    velocityLabel: 'ESTABLISHED',
    growthDeltaText: 'Industry Standard ML Lifecycle Platform',
  },

  // ==========================================
  // 3. DEVOPS, CLOUD-NATIVE & KUBERNETES INFRASTRUCTURE
  // ==========================================
  {
    id: 'kubernetes/kubernetes',
    fullName: 'kubernetes/kubernetes',
    name: 'kubernetes',
    owner: 'kubernetes',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/13629408?v=4',
    description: 'Production-Grade Container Scheduling and Management. The foundation of modern cloud-native infrastructure.',
    url: 'https://github.com/kubernetes/kubernetes',
    stars: 114000,
    forks: 40000,
    openIssues: 2100,
    language: 'Go',
    topics: ['cloud-native', 'container-orchestration', 'devops', 'kubernetes', 'cncf'],
    updatedAt: new Date().toISOString(),
    createdAt: '2014-06-06T00:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'architecture'],
    isVerified: true,
    velocityScore: 92,
    velocityLabel: 'ESTABLISHED',
    hasBigUpdate: true,
    growthDeltaText: '114k stars • Backbone of Global Cloud Infrastructure',
  },
  {
    id: 'opentofu/opentofu',
    fullName: 'opentofu/opentofu',
    name: 'opentofu',
    owner: 'opentofu',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/144670054?v=4',
    description: 'OpenTofu lets you declaratively manage your cloud infrastructure using code. Open-source Linux Foundation community fork of Terraform.',
    url: 'https://github.com/opentofu/opentofu',
    stars: 24200,
    forks: 1100,
    openIssues: 120,
    language: 'Go',
    topics: ['iac', 'infrastructure-as-code', 'opentofu', 'linux-foundation', 'terraform-alternative'],
    updatedAt: new Date().toISOString(),
    createdAt: '2023-08-15T00:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'trending'],
    isVerified: true,
    velocityScore: 96,
    velocityLabel: 'HOT RISING',
    growthDeltaText: '+40 stars/day • LF Open-Source IaC Standard',
  },
  {
    id: 'cilium/cilium',
    fullName: 'cilium/cilium',
    name: 'cilium',
    owner: 'cilium',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/17983637?v=4',
    description: 'eBPF-based Networking, Observability, and Security for Kubernetes. Replaces kube-proxy with high-performance kernel-level packet routing.',
    url: 'https://github.com/cilium/cilium',
    stars: 21800,
    forks: 3100,
    openIssues: 450,
    language: 'Go',
    topics: ['ebpf', 'kubernetes-cni', 'service-mesh', 'network-security', 'observability'],
    updatedAt: new Date().toISOString(),
    createdAt: '2016-04-10T00:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'architecture', 'trending'],
    isVerified: true,
    velocityScore: 95,
    velocityLabel: 'HOT RISING',
    hasBigUpdate: true,
    growthDeltaText: 'Top eBPF Kubernetes Networking Standard',
  },
  {
    id: 'argoproj/argo-cd',
    fullName: 'argoproj/argo-cd',
    name: 'argo-cd',
    owner: 'argoproj',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/30269780?v=4',
    description: 'Declarative, GitOps continuous delivery tool for Kubernetes. Automatically synchronizes cluster states with Git repositories.',
    url: 'https://github.com/argoproj/argo-cd',
    stars: 19400,
    forks: 5800,
    openIssues: 680,
    language: 'Go',
    topics: ['gitops', 'continuous-delivery', 'kubernetes', 'cd-pipeline', 'cncf-graduated'],
    updatedAt: new Date().toISOString(),
    createdAt: '2018-02-01T00:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'architecture'],
    isVerified: true,
    velocityScore: 94,
    velocityLabel: 'ESTABLISHED',
    hasBigUpdate: true,
    growthDeltaText: 'CNCF Graduated GitOps Controller',
  },
  {
    id: 'crossplane/crossplane',
    fullName: 'crossplane/crossplane',
    name: 'crossplane',
    owner: 'crossplane',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/45173160?v=4',
    description: 'The Cloud Native Control Plane framework. Turn any Kubernetes cluster into a universal control plane to provision AWS, GCP, Azure, and SQL databases.',
    url: 'https://github.com/crossplane/crossplane',
    stars: 9800,
    forks: 1200,
    openIssues: 190,
    language: 'Go',
    topics: ['control-plane', 'kubernetes-crd', 'multi-cloud', 'platform-engineering', 'iac'],
    updatedAt: new Date().toISOString(),
    createdAt: '2018-12-05T00:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'architecture'],
    isVerified: true,
    velocityScore: 92,
    velocityLabel: 'HOT RISING',
    growthDeltaText: 'Universal Cloud Control Plane',
  },
  {
    id: 'derailed/k9s',
    fullName: 'derailed/k9s',
    name: 'k9s',
    owner: 'derailed',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/10283204?v=4',
    description: 'Kubernetes CLI To Manage Your Clusters In Style! Terminal-based UI to observe, tail logs, port-forward, and debug pods in real time.',
    url: 'https://github.com/derailed/k9s',
    stars: 29500,
    forks: 1800,
    openIssues: 120,
    language: 'Go',
    topics: ['terminal-ui', 'kubernetes-management', 'cli', 'debugging-tool', 'devops'],
    updatedAt: new Date().toISOString(),
    createdAt: '2019-01-20T00:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'trending'],
    isVerified: true,
    velocityScore: 94,
    velocityLabel: 'HOT RISING',
    growthDeltaText: '29.5k stars • #1 Kubernetes Terminal UI',
  },
  {
    id: 'aquasecurity/trivy',
    fullName: 'aquasecurity/trivy',
    name: 'trivy',
    owner: 'aquasecurity',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/12788831?v=4',
    description: 'Find vulnerabilities, misconfigurations, secrets, SBOM in containers, Kubernetes, code repositories, clouds and more.',
    url: 'https://github.com/aquasecurity/trivy',
    stars: 25400,
    forks: 2300,
    openIssues: 210,
    language: 'Go',
    topics: ['vulnerability-scanner', 'sbom', 'container-security', 'devsecops', 'kubernetes-security'],
    updatedAt: new Date().toISOString(),
    createdAt: '2019-04-10T00:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'trending'],
    isVerified: true,
    velocityScore: 95,
    velocityLabel: 'ESTABLISHED',
    hasBigUpdate: true,
    growthDeltaText: 'Industry Standard Container & SBOM Scanner',
  },
  {
    id: 'falcosecurity/falco',
    fullName: 'falcosecurity/falco',
    name: 'falco',
    owner: 'falcosecurity',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/35799981?v=4',
    description: 'Cloud Native Runtime Security. Detects unexpected application behavior and alerts on threats in real time using eBPF kernel event probes.',
    url: 'https://github.com/falcosecurity/falco',
    stars: 7600,
    forks: 980,
    openIssues: 140,
    language: 'C++',
    topics: ['runtime-security', 'ebpf', 'threat-detection', 'kubernetes-security', 'cncf-graduated'],
    updatedAt: new Date().toISOString(),
    createdAt: '2016-05-15T00:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'architecture'],
    isVerified: true,
    velocityScore: 91,
    velocityLabel: 'COMMUNITY PICK',
    growthDeltaText: 'CNCF Graduated Runtime Threat Detection',
  },
  {
    id: 'prometheus/prometheus',
    fullName: 'prometheus/prometheus',
    name: 'prometheus',
    owner: 'prometheus',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/3380462?v=4',
    description: 'The Prometheus monitoring system and time series database. Industry standard metric scraping, alerting, and PromQL engine.',
    url: 'https://github.com/prometheus/prometheus',
    stars: 57800,
    forks: 9200,
    openIssues: 780,
    language: 'Go',
    topics: ['monitoring', 'metrics', 'time-series', 'alerting', 'cncf-graduated'],
    updatedAt: new Date().toISOString(),
    createdAt: '2012-11-24T00:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'architecture'],
    isVerified: true,
    velocityScore: 92,
    velocityLabel: 'ESTABLISHED',
    growthDeltaText: 'Global Standard Metrics & Alerting Engine',
  },
  {
    id: 'grafana/grafana',
    fullName: 'grafana/grafana',
    name: 'grafana',
    owner: 'grafana',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/7195757?v=4',
    description: 'The open and composable observability and data visualization platform. Visualize metrics, logs, and traces from any source.',
    url: 'https://github.com/grafana/grafana',
    stars: 65200,
    forks: 12100,
    openIssues: 1200,
    language: 'TypeScript',
    topics: ['dashboards', 'visualization', 'observability', 'metrics', 'tracing'],
    updatedAt: new Date().toISOString(),
    createdAt: '2013-12-11T00:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'architecture'],
    isVerified: true,
    velocityScore: 93,
    velocityLabel: 'ESTABLISHED',
    growthDeltaText: '65.2k stars • Universal Observability Dashboard',
  },
  {
    id: 'open-telemetry/opentelemetry-collector',
    fullName: 'open-telemetry/opentelemetry-collector',
    name: 'opentelemetry-collector',
    owner: 'open-telemetry',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/50747424?v=4',
    description: 'OpenTelemetry Collector offers a vendor-agnostic implementation on how to receive, process and export telemetry data (traces, metrics, logs).',
    url: 'https://github.com/open-telemetry/opentelemetry-collector',
    stars: 5400,
    forks: 1900,
    openIssues: 280,
    language: 'Go',
    topics: ['opentelemetry', 'otel', 'distributed-tracing', 'observability-pipeline', 'cncf'],
    updatedAt: new Date().toISOString(),
    createdAt: '2019-05-01T00:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'architecture'],
    isVerified: true,
    velocityScore: 94,
    velocityLabel: 'HOT RISING',
    growthDeltaText: 'Universal OpenTelemetry Pipeline Standard',
  },
  {
    id: 'traefik/traefik',
    fullName: 'traefik/traefik',
    name: 'traefik',
    owner: 'traefik',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/15243160?v=4',
    description: 'The Cloud Native Application Proxy. Modern HTTP reverse proxy and load balancer that integrates with Docker, Kubernetes, and Consul.',
    url: 'https://github.com/traefik/traefik',
    stars: 53200,
    forks: 5100,
    openIssues: 410,
    language: 'Go',
    topics: ['reverse-proxy', 'load-balancer', 'ingress-controller', 'docker', 'kubernetes'],
    updatedAt: new Date().toISOString(),
    createdAt: '2015-09-10T00:00:00Z',
    category: 'devops-infra',
    categories: ['devops-infra', 'architecture'],
    isVerified: true,
    velocityScore: 92,
    velocityLabel: 'ESTABLISHED',
    growthDeltaText: '53.2k stars • Cloud-Native Edge Router',
  },

  // ==========================================
  // 4. ARCHITECTURE, SYSTEM DESIGN & BEST PRACTICES
  // ==========================================
  {
    id: 'donnemartin/system-design-primer',
    fullName: 'donnemartin/system-design-primer',
    name: 'system-design-primer',
    owner: 'donnemartin',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/5449100?v=4',
    description: 'Learn how to design large-scale systems. Prep for the system design interview. Includes real-world architectures (Twitter, Uber, Netflix).',
    url: 'https://github.com/donnemartin/system-design-primer',
    stars: 284000,
    forks: 46000,
    openIssues: 480,
    language: 'Python',
    topics: ['system-design', 'interview-prep', 'scalability', 'distributed-systems', 'architecture'],
    updatedAt: new Date().toISOString(),
    createdAt: '2017-02-26T00:00:00Z',
    category: 'architecture',
    categories: ['architecture', 'trending'],
    isVerified: true,
    velocityScore: 98,
    velocityLabel: 'ESTABLISHED',
    hasBigUpdate: true,
    growthDeltaText: '284k stars • The Bible of System Architecture',
    socialSignals: { hnTopScore: 950 },
  },
  {
    id: 'kamranahmedse/developer-roadmap',
    fullName: 'kamranahmedse/developer-roadmap',
    name: 'developer-roadmap',
    owner: 'kamranahmedse',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/4921183?v=4',
    description: 'Interactive roadmaps, guides and other educational content to help developers grow in their careers: AI, DevOps, Backend, Frontend, Cloud.',
    url: 'https://github.com/kamranahmedse/developer-roadmap',
    stars: 308000,
    forks: 40000,
    openIssues: 590,
    language: 'TypeScript',
    topics: ['roadmap', 'devops-roadmap', 'ai-roadmap', 'learning-paths', 'career-guide'],
    updatedAt: new Date().toISOString(),
    createdAt: '2017-03-15T00:00:00Z',
    category: 'architecture',
    categories: ['architecture', 'trending'],
    isVerified: true,
    velocityScore: 99,
    velocityLabel: 'ESTABLISHED',
    growthDeltaText: '308k stars • #1 Career & Learning Roadmap',
  },
  {
    id: 'bregman-arie/devops-exercises',
    fullName: 'bregman-arie/devops-exercises',
    name: 'devops-exercises',
    owner: 'bregman-arie',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/10331009?v=4',
    description: 'Linux, Jenkins, AWS, SRE, Prometheus, Docker, Python, Ansible, Git, Kubernetes, Terraform, OpenStack, SQL, NoSQL questions and exercises.',
    url: 'https://github.com/bregman-arie/devops-exercises',
    stars: 68400,
    forks: 16500,
    openIssues: 95,
    language: 'Python',
    topics: ['devops-interview', 'sre-exercises', 'kubernetes', 'docker', 'ansible', 'terraform'],
    updatedAt: new Date().toISOString(),
    createdAt: '2020-03-10T00:00:00Z',
    category: 'architecture',
    categories: ['architecture', 'devops-infra'],
    isVerified: true,
    velocityScore: 94,
    velocityLabel: 'HOT RISING',
    growthDeltaText: '68.4k stars • Complete SRE & DevOps Knowledge Base',
  },
  {
    id: 'trimstray/the-book-of-secret-knowledge',
    fullName: 'trimstray/the-book-of-secret-knowledge',
    name: 'the-book-of-secret-knowledge',
    owner: 'trimstray',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/11189421?v=4',
    description: 'A collection of inspiring lists, manuals, cheatsheets, blogs, hacks, one-liners, cli/web tools and more for CLI power users and sysadmins.',
    url: 'https://github.com/trimstray/the-book-of-secret-knowledge',
    stars: 162000,
    forks: 17200,
    openIssues: 45,
    language: 'Shell',
    topics: ['cheatsheet', 'sysadmin', 'security', 'command-line', 'oneliners', 'devops'],
    updatedAt: new Date().toISOString(),
    createdAt: '2018-09-01T00:00:00Z',
    category: 'architecture',
    categories: ['architecture', 'devops-infra'],
    isVerified: true,
    velocityScore: 96,
    velocityLabel: 'ESTABLISHED',
    growthDeltaText: '162k stars • Ultimate Dev & Ops Cheatsheet Compendium',
  },
  {
    id: 'awesome-selfhosted/awesome-selfhosted',
    fullName: 'awesome-selfhosted/awesome-selfhosted',
    name: 'awesome-selfhosted',
    owner: 'awesome-selfhosted',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/10492120?v=4',
    description: 'A list of Free Software network services and web applications which can be hosted locally. Self-hosting is the process of locally hosting services.',
    url: 'https://github.com/awesome-selfhosted/awesome-selfhosted',
    stars: 232000,
    forks: 11400,
    openIssues: 180,
    language: 'Markdown',
    topics: ['self-hosted', 'open-source', 'homelab', 'privacy', 'cloud-alternative'],
    updatedAt: new Date().toISOString(),
    createdAt: '2015-05-10T00:00:00Z',
    category: 'architecture',
    categories: ['architecture', 'trending'],
    isVerified: true,
    velocityScore: 97,
    velocityLabel: 'ESTABLISHED',
    growthDeltaText: '232k stars • The Definitive Self-Hosting Directory',
  },
  {
    id: 'ibraheemdev/modern-unix',
    fullName: 'ibraheemdev/modern-unix',
    name: 'modern-unix',
    owner: 'ibraheemdev',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/41551253?v=4',
    description: 'A collection of modern alternatives to common unix tools: bat (cat), eza (ls), ripgrep (grep), fd (find), bottom (top), delta (diff), zoxide (cd).',
    url: 'https://github.com/ibraheemdev/modern-unix',
    stars: 44200,
    forks: 1400,
    openIssues: 32,
    language: 'Markdown',
    topics: ['rust-tools', 'modern-cli', 'terminal-productivity', 'unix-tools'],
    updatedAt: new Date().toISOString(),
    createdAt: '2021-04-12T00:00:00Z',
    category: 'architecture',
    categories: ['architecture', 'devops-infra'],
    isVerified: true,
    velocityScore: 93,
    velocityLabel: 'COMMUNITY PICK',
    growthDeltaText: '44.2k stars • Modern Developer CLI Stack',
  },
  {
    id: 'mxschmitt/sre-interview-prep',
    fullName: 'mxschmitt/sre-interview-prep',
    name: 'sre-interview-prep',
    owner: 'mxschmitt',
    ownerAvatar: 'https://avatars.githubusercontent.com/u/17984829?v=4',
    description: 'Curated Site Reliability Engineering (SRE) interview preparation guide with deep dives into Linux internals, networking, troubleshooting, and scale.',
    url: 'https://github.com/mxschmitt/sre-interview-prep',
    stars: 9800,
    forks: 1100,
    openIssues: 12,
    language: 'Markdown',
    topics: ['sre', 'linux-internals', 'incident-response', 'system-troubleshooting'],
    updatedAt: new Date().toISOString(),
    createdAt: '2021-01-15T00:00:00Z',
    category: 'architecture',
    categories: ['architecture', 'devops-infra'],
    isVerified: true,
    velocityScore: 91,
    velocityLabel: 'COMMUNITY PICK',
    growthDeltaText: 'Complete SRE & Production Engineering Guide',
  },
];
